// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_repository_stars.sql

package dbs

import (
	"context"
	"time"
)

const githubRepositoryStars = `-- name: GithubRepositoryStars :one
SELECT stargazers_count
FROM github_repository_stars
WHERE owner = $1
  AND repo = $2
`

type GithubRepositoryStarsParams struct {
	Owner string
	Repo  string
}

func (q *Queries) GithubRepositoryStars(ctx context.Context, arg GithubRepositoryStarsParams) (int32, error) {
	row := q.queryRow(ctx, q.githubRepositoryStarsStmt, githubRepositoryStars, arg.Owner, arg.Repo)
	var stargazers_count int32
	err := row.Scan(&stargazers_count)
	return stargazers_count, err
}

const githubRepositoryStarsAll = `-- name: GithubRepositoryStarsAll :many
SELECT owner, repo, stargazers_count
FROM github_repository_stars
`

type GithubRepositoryStarsAllRow struct {
	Owner           string
	Repo            string
	StargazersCount int32
}

func (q *Queries) GithubRepositoryStarsAll(ctx context.Context) ([]GithubRepositoryStarsAllRow, error) {
	rows, err := q.query(ctx, q.githubRepositoryStarsAllStmt, githubRepositoryStarsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubRepositoryStarsAllRow
	for rows.Next() {
		var i GithubRepositoryStarsAllRow
		if err := rows.Scan(&i.Owner, &i.Repo, &i.StargazersCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const githubRepositoryStarsUpsert = `-- name: GithubRepositoryStarsUpsert :exec
INSERT INTO github_repository_stars (owner, repo, stargazers_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (owner, repo) DO UPDATE
    SET stargazers_count = excluded.stargazers_count,
        updated_at       = excluded.updated_at
`

type GithubRepositoryStarsUpsertParams struct {
	Owner           string
	Repo            string
	StargazersCount int32
	CreatedAt       time.Time
}

func (q *Queries) GithubRepositoryStarsUpsert(ctx context.Context, arg GithubRepositoryStarsUpsertParams) error {
	_, err := q.exec(ctx, q.githubRepositoryStarsUpsertStmt, githubRepositoryStarsUpsert,
		arg.Owner,
		arg.Repo,
		arg.StargazersCount,
		arg.CreatedAt,
	)
	return err
}
