// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: github_repository_stars.sql

package dbs

import (
	"context"
	"time"
)

const getGithubRepositoryStars = `-- name: GetGithubRepositoryStars :many
SELECT owner, repo, stargazers_count, updated_at
FROM github_repository_stars
`

func (q *Queries) GetGithubRepositoryStars(ctx context.Context) ([]GithubRepositoryStar, error) {
	rows, err := q.query(ctx, q.getGithubRepositoryStarsStmt, getGithubRepositoryStars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubRepositoryStar
	for rows.Next() {
		var i GithubRepositoryStar
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.StargazersCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGithubRepositoryStars = `-- name: UpsertGithubRepositoryStars :exec
INSERT INTO github_repository_stars (owner, repo, stargazers_count, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner, repo) DO UPDATE
SET stargazers_count = EXCLUDED.stargazers_count,
    updated_at       = EXCLUDED.updated_at
`

type UpsertGithubRepositoryStarsParams struct {
	Owner           string
	Repo            string
	StargazersCount int32
	UpdatedAt       time.Time
}

func (q *Queries) UpsertGithubRepositoryStars(ctx context.Context, arg UpsertGithubRepositoryStarsParams) error {
	_, err := q.exec(ctx, q.upsertGithubRepositoryStarsStmt, upsertGithubRepositoryStars,
		arg.Owner,
		arg.Repo,
		arg.StargazersCount,
		arg.UpdatedAt,
	)
	return err
}
