// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbs

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type SocialProvider string

const (
	SocialProviderGithub    SocialProvider = "github"
	SocialProviderGitlab    SocialProvider = "gitlab"
	SocialProviderBitbucket SocialProvider = "bitbucket"
	SocialProviderFigma     SocialProvider = "figma"
	SocialProviderDribbble  SocialProvider = "dribbble"
	SocialProviderBehance   SocialProvider = "behance"
	SocialProviderLinkedin  SocialProvider = "linkedin"
	SocialProviderXing      SocialProvider = "xing"
	SocialProviderGoogle    SocialProvider = "google"
)

func (e *SocialProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SocialProvider(s)
	case string:
		*e = SocialProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for SocialProvider: %T", src)
	}
	return nil
}

type NullSocialProvider struct {
	SocialProvider SocialProvider
	Valid          bool // Valid is true if SocialProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSocialProvider) Scan(value interface{}) error {
	if value == nil {
		ns.SocialProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SocialProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSocialProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SocialProvider), nil
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type UserOnlineDailyCountStat struct {
	CreatedAt time.Time
	UserCount int64
}

type UserOnlineDailyStat struct {
	CreatedAt time.Time
	UserID    int64
}

type UserOnlineHourlyStat struct {
	UserID    int64
	CreatedAt time.Time
}

type UserSocialProfile struct {
	ID                   int64
	UserID               int64
	SocialProvider       SocialProvider
	SocialProviderUserID string
	Email                string
	Username             string
	Name                 string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            sql.NullTime
}

type UserSocialProfileChangeHistory struct {
	ID                  int64
	UserID              int64
	UserSocialProfileID int64
	Email               string
	Username            string
	Name                string
	CreatedAt           time.Time
	DeletedAt           sql.NullTime
}
