ansible-ping:
	ansible -i ./scripts/ansible/hosts.ini all -m ping

ansible-git-pull:
	ansible-playbook -i ./scripts/ansible/hosts.ini ./scripts/ansible/git-pull.yml

ansible-install-docker:
	ansible-playbook -i ./scripts/ansible/hosts.ini ./scripts/ansible/install-docker.yml

ansible-install-go:
	ansible-playbook -i ./scripts/ansible/hosts.ini ./scripts/ansible/install-go.yml

ansible-install-nodejs:
	ansible-playbook -i ./scripts/ansible/hosts.ini ./scripts/ansible/install-nodejs.yml
