// Code generated by qtc from "company_code.go.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package dev

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamCompanyCode(qw422016 *qt422016.Writer, pairs []*CompanyCodePair) {
	qw422016.N().S(`// Code generated by make generate-organizers. DO NOT EDIT.

package organizers

var (
	CompanyAliasToCodeMap = map[string]int64{
`)
	for _, pair := range pairs {
		qw422016.N().S(` `)
		qw422016.N().S(`"`)
		qw422016.E().S(pair.Alias)
		qw422016.N().S(`":`)
		qw422016.N().DL(pair.ID)
		qw422016.N().S(`, //`)
		qw422016.N().S(` `)
		qw422016.E().S(pair.Name)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
	}
)
`)
}

func WriteCompanyCode(qq422016 qtio422016.Writer, pairs []*CompanyCodePair) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamCompanyCode(qw422016, pairs)
	qt422016.ReleaseWriter(qw422016)
}

func CompanyCode(pairs []*CompanyCodePair) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteCompanyCode(qb422016, pairs)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
