// Code generated by qtc from "logos_search.md.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package dev

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamLogosSearch(qw422016 *qt422016.Writer, pairs []*CompanyCodePair) {
	qw422016.N().S(`    `)
	qw422016.N().S(`| Name | Logo |`)
	qw422016.N().S(`
`)
	for _, pair := range pairs {
		qw422016.N().S(`| [`)
		qw422016.E().S(pair.Name)
		qw422016.N().S(`](https://www.linkedin.com/company/`)
		qw422016.E().S(pair.Alias)
		qw422016.N().S(`/) | [search on Google](`)
		qw422016.E().S(googleSearchLogos(pair.Name))
		qw422016.N().S(`) |`)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
}

func WriteLogosSearch(qq422016 qtio422016.Writer, pairs []*CompanyCodePair) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamLogosSearch(qw422016, pairs)
	qt422016.ReleaseWriter(qw422016)
}

func LogosSearch(pairs []*CompanyCodePair) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteLogosSearch(qb422016, pairs)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
