// Code generated by qtc from "organizers-company-v2.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamOrganizersCompanyV2(qw422016 *qt422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">

<head>
	<title>`)
	qw422016.E().S(company.Name)
	qw422016.N().S(` – company using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` | ReadyToTouch</title>
	<meta name="description" content="Improve your chances of getting a job by connecting with `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` developers from `)
	qw422016.E().S(company.Name)
	qw422016.N().S(` and receiving further recommendations.">

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="author" type="text/plain" href="https://readytotouch.com/humans.txt"/>
	<meta property="og:image" content="/assets/images/og/organizers-light.jpg">

    `)
	streamfavicon(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersFonts(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersCompanyV2Styles(qw422016)
	qw422016.N().S(`
    <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.52.0"></script>
    `)
	streamplausibleAnalytics(qw422016)
	qw422016.N().S(`
    `)
	streamga(qw422016)
	qw422016.N().S(`
</head>

<body class="organizer-companies-inner">
<main class="main-wrapper">
<header class="header">
  <div class="header__wrapper">
    <a href="/organizers" class="header__logo">
      <img
        width="129"
        height="32"
        class="header__logo-img"
        src="/assets/images/pages/organizer/`)
	qw422016.E().S(organizerFeature.Organizer.Logo)
	qw422016.N().S(`"
        alt="organizer logo"
      />
    </a>
    <ul class="header__nav">
      <li class="header__nav-item">
        <a href="/organizers/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/companies" class="header__nav-link active">Companies</a>
      </li>
      <li class="header__nav-item">
        <a href="/organizers/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/jobs" class="header__nav-link">Jobs</a>
      </li>
      <li class="header__nav-item">
        <a href="/organizers/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/communities" class="header__nav-link">Communities</a>
      </li>
    </ul>
    `)
	streamorganizersHeaderStars(qw422016)
	qw422016.N().S(`
    `)
	if len(headerProfiles) > 0 {
		qw422016.N().S(`
    `)
		streamorganizersHeaderProfile(qw422016, headerProfiles)
		qw422016.N().S(`
    `)
	} else {
		qw422016.N().S(`
    <a href="/organizers/`)
		qw422016.E().S(organizerFeature.Organizer.Alias)
		qw422016.N().S(`/welcome`)
		qw422016.E().S(authQueryParams)
		qw422016.N().S(`" class="button button--small-padding button--black header__login-button">Log in</a>
    `)
	}
	qw422016.N().S(`
  </div>
</header>

<div class="container">
  <nav aria-label="breadcrumb" aria-labelledby="navigation through the bread crumbs" class="breadcrumb">
    <ul class="breadcrumb__list">
      <li class="breadcrumb__item">
        <a class="breadcrumb__link" href="/">Main</a>
      </li>
      <li class="breadcrumb__item">
        <a class="breadcrumb__link" href="/organizers">Organizers</a>
      </li>
      <li class="breadcrumb__item">
        <a class="breadcrumb__link" href="javascript:void(0);">`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(`</a>
      </li>
      <li class="breadcrumb__item">
        <a class="breadcrumb__link" href="`)
	qw422016.E().S(organizerFeature.Path)
	qw422016.N().S(`">`)
	qw422016.E().S(organizerFeature.Title)
	qw422016.N().S(`</a>
      </li>
      <li class="breadcrumb__item">
        <span class="breadcrumb__page" aria-current="page">`)
	qw422016.E().S(company.Name)
	qw422016.N().S(`</span>
      </li>
    </ul>
  </nav>
</div>

<section class="companies-cards">
  <div class="container companies-cards__container">
<div class="js-company card"
     data-company-id="`)
	qw422016.N().DL(company.ID)
	qw422016.N().S(`"
     data-company-name="`)
	qw422016.E().S(company.Name)
	qw422016.N().S(`"
     data-company-type="`)
	qw422016.E().S(string(company.Type))
	qw422016.N().S(`"
>
  <aside class="card__action">
    `)
	if favorite {
		qw422016.N().S(`
      <button class="js-company-favorite favorite card__action-button button-group__item in-favorite" title="Remove from favorites">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
          <path
            d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
          />
        </svg>
      </button>
    `)
	} else {
		qw422016.N().S(`
      <button class="js-company-favorite favorite card__action-button button-group__item" title="Add to favorite">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
          <path
            d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
          />
        </svg>
      </button>
    `)
	}
	qw422016.N().S(`

    `)
	qw422016.N().S(`
  </aside>
  <figure class="card__header">
    <div class="card__image-overlay">
      <img
        class="card__image"
        alt="card image preview icon"
		src="`)
	qw422016.E().S(logo(company.Logo))
	qw422016.N().S(`"
      />
    </div>
    <figcaption class="card__header-caption">
      <a href="`)
	qw422016.E().S(organizerFeature.Path)
	qw422016.N().S(`/`)
	qw422016.E().S(company.LinkedInProfile.Alias)
	qw422016.N().S(`" class="card__headline card__headline--title">`)
	qw422016.E().S(company.Name)
	qw422016.N().S(`</a>
    </figcaption>
  </figure>
	<div class="card__top-links">
		<a href="`)
	qw422016.E().S(company.Website)
	qw422016.N().S(`" target="_blank" class="card__top-link button-link">Website</a>
		`)
	if company.Careers == "" {
		qw422016.N().S(`
			<span class="card__top-link button-link disabled">Careers</span>
		`)
	} else {
		qw422016.N().S(`
			<a href="`)
		qw422016.E().S(company.Careers)
		qw422016.N().S(`" target="_blank" class="card__top-link button-link">Careers</a>
		`)
	}
	qw422016.N().S(`
		`)
	if company.About == "" {
		qw422016.N().S(`
			<span class="card__top-link button-link disabled">About</span>
		`)
	} else {
		qw422016.N().S(`
			<a href="`)
		qw422016.E().S(company.About)
		qw422016.N().S(`" target="_blank" class="card__top-link button-link">About</a>
		`)
	}
	qw422016.N().S(`
		`)
	if company.Blog == "" {
		qw422016.N().S(`
			<span class="card__top-link button-link disabled">Dev Blog</span>
		`)
	} else {
		qw422016.N().S(`
			<a href="`)
		qw422016.E().S(company.Blog)
		qw422016.N().S(`" target="_blank" class="card__top-link button-link">Dev Blog</a>
		`)
	}
	qw422016.N().S(`
	</div>
  <div class="card__info">
    <figure class="card__figure">
      <img
        class="card__icon"
        alt="card type icon"
        width="16"
        height="16"
        src="/assets/images/pages/vacancy/building.svg"
      />
      <figcaption class="card__figcaption">`)
	qw422016.E().S(companyTypeName[company.Type])
	qw422016.N().S(`</figcaption>
    </figure>
    <figure class="card__figure">
      <img
        class="card__icon"
        alt="card type icon"
        width="16"
        height="16"
        src="/assets/images/pages/vacancy/company-type.svg"
      />
      <figcaption class="card__figcaption">`)
	qw422016.E().S(industryNames(company.Industries))
	qw422016.N().S(`</figcaption>
    </figure>
  </div>
  <p class="card__text card__text--full-text">
	`)
	qw422016.E().S(company.ShortDescription)
	qw422016.N().S(`
  </p>
</div>
<div class="cards-group">
	<div class="card">
		<ul class="card__links-group">
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/linkedin.svg"
					/>
					<a href="https://www.linkedin.com/company/`)
	qw422016.E().S(company.LinkedInProfile.Alias)
	qw422016.N().S(`/" target="_blank" class="card__links-link">LinkedIn</a>
					`)
	if company.LinkedInProfile.Verified {
		qw422016.N().S(`
					<a href="https://www.linkedin.com/company/`)
		qw422016.E().S(company.LinkedInProfile.Alias)
		qw422016.N().S(`/about" target="_blank" class="card__links-link card__links-link--verify">
						<img
							class="card__links-icon"
							alt="icon"
							src="/assets/images/pages/organizer/verified-icon.png"
						/>
					</a>
					`)
	}
	qw422016.N().S(`
				</div>
				<ul class="card__links-item-info">
					<li class="card__link-stats-item">`)
	qw422016.E().S(formatLinkedInFollowers(company.LinkedInProfile.Followers))
	qw422016.N().S(` followers</li>
					<li class="card__link-stats-item">`)
	qw422016.E().S(formatLinkedInEmployees(company.LinkedInProfile.Employees))
	qw422016.N().S(` employees</li>
					<li class="card__link-stats-item">`)
	qw422016.E().S(formatLinkedInAssociatedMembers(company.LinkedInProfile.AssociatedMembers))
	qw422016.N().S(` associated members</li>
				</ul>
			</li>
			<li class="card__links-item">
				<a href="https://www.linkedin.com/company/`)
	qw422016.E().S(company.LinkedInProfile.Alias)
	qw422016.N().S(`/" target="_blank" class="button-link card__links-link">Overview</a>
			</li>
			<li class="card__links-item">
				<a href="`)
	qw422016.E().S(linkedinConnectionsURL([]Company{company}, nil))
	qw422016.N().S(`" target="_blank" class="button-link card__links-link">Connections (current employees)</a>
				<img
					class="card__links-icon"
					alt="language icon"
					width="20"
					height="20"
					src="/assets/images/pages/organizer/language.svg"
				/>
			</li>
			<li class="card__links-item">
				<a href="`)
	qw422016.E().S(linkedinConnectionsURL([]Company{company}, ukrainianUniversities))
	qw422016.N().S(`" target="_blank" class="button-link card__links-link">Connections (current employees) 🇺🇦</a>
			</li>
			<li class="card__links-item">
				<a href="`)
	qw422016.E().S(linkedinConnectionsURL([]Company{company}, czechUniversities))
	qw422016.N().S(`" target="_blank" class="button-link card__links-link">Connections (current employees) 🇨🇿</a>
			</li>
			<li class="card__links-item">
				<a href="`)
	qw422016.E().S(linkedinConnectionsFormerEmployeesURL([]Company{company}))
	qw422016.N().S(`" target="_blank" class="button-link card__links-link">Connections (former employees)</a>
			</li>
			<li class="card__links-item">
				<a href="`)
	qw422016.E().S(linkedinJobsURL([]Company{company}, string(organizerFeature.Organizer.LanguageTitleKeywords)))
	qw422016.N().S(`" target="_blank" class="button-link card__links-link">Jobs</a>
			</li>
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group">
			`)
	if company.GitHubProfile.Login == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title card__links-item--disabled">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="github icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/github.svg"
					/>
					<span class="card__links-link">GitHub</span>
				</div>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Overview</span>
				<a href="`)
		qw422016.E().S(googleSearchGitHub(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Repositories (?)</span>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="github icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/github.svg"
					/>
					`)
		if company.GitHubProfile.Verified {
			qw422016.N().S(`
					<span class="card__links-link card__links-link--verify">
						<img
							class="card__links-icon"
							alt="icon"
							src="/assets/images/pages/organizer/verified.png"
						/>
					</span>
					`)
		}
		qw422016.N().S(`
					<a href="https://github.com/`)
		qw422016.E().S(company.GitHubProfile.Login)
		qw422016.N().S(`" target="_blank" class="card__links-link">GitHub</a>
				</div>
			</li>
			<li class="card__links-item">
				<a href="https://github.com/`)
		qw422016.E().S(company.GitHubProfile.Login)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Overview</a>
			</li>
			<li class="card__links-item">
				<a href="https://github.com/orgs/`)
		qw422016.E().S(company.GitHubProfile.Login)
		qw422016.N().S(`/repositories?q=lang:`)
		qw422016.E().S(organizerFeature.Organizer.GitHubAlias)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Repositories (`)
		qw422016.N().D(fetchGitHubRepositoriesCount(company, organizerFeature.Organizer.Language))
		qw422016.N().S(`)</a>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group">
			`)
	if company.BlindProfile.Alias == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title card__links-item--disabled">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/blind.png"
					/>
					<span class="card__links-link">Blind</span>
				</div>
				<ul class="card__links-item-info">
					<li class="card__link-stats-item">??? employees</li>
					<li class="card__link-stats-item">$??K ~ $???K a year</li>
					<li class="card__link-stats-item">??? reviews</li>
				</ul>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Overview</span>
				<a href="`)
		qw422016.E().S(googleSearchBlind(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Reviews</span>
				<span class="card__links-link-star">⭐ ?.?</span>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/blind.png"
					/>
					<a href="https://www.teamblind.com/company/`)
		qw422016.E().S(company.BlindProfile.Alias)
		qw422016.N().S(`" target="_blank" class="card__links-link">Blind</a>
				</div>
				<ul class="card__links-item-info">
					<li class="card__link-stats-item">`)
		qw422016.E().S(formatBlindEmployees(company.BlindProfile.Employees))
		qw422016.N().S(` employees</li>
					<li class="card__link-stats-item">`)
		qw422016.E().S(formatBlindSalary(company.BlindProfile.Salary))
		qw422016.N().S(`</li>
					<li class="card__link-stats-item">`)
		qw422016.E().S(formatBlindReviews(company.BlindProfile.Reviews))
		qw422016.N().S(` reviews</li>
				</ul>
			</li>
			<li class="card__links-item">
				<a href="https://www.teamblind.com/company/`)
		qw422016.E().S(company.BlindProfile.Alias)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Overview</a>
			</li>
			<li class="card__links-item">
				<a href="https://www.teamblind.com/company/`)
		qw422016.E().S(company.BlindProfile.Alias)
		qw422016.N().S(`/reviews" target="_blank" class="button-link card__links-link">Reviews</a>
				<span class="card__links-link-star">⭐ `)
		qw422016.E().S(company.BlindProfile.ReviewsRate)
		qw422016.N().S(`</span>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group">
			`)
	if company.LevelsFyiProfile.Alias == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title card__links-item--disabled">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/levels.png"
					/>
					<span class="card__links-link">Levels.fyi</span>
				</div>
				<ul class="card__links-item-info">
					<li class="card__link-stats-item">??? employees</li>
				</ul>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Overview</span>
				<a href="`)
		qw422016.E().S(googleSearchLevelsFyi(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Jobs</span>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/levels.png"
					/>
					<a href="https://www.levels.fyi/companies/`)
		qw422016.E().S(company.LevelsFyiProfile.Alias)
		qw422016.N().S(`" target="_blank" class="card__links-link">Levels.fyi</a>
				</div>
				<ul class="card__links-item-info">
					<li class="card__link-stats-item">`)
		qw422016.E().S(formatLevelsFyiEmployees(company.LevelsFyiProfile.Employees))
		qw422016.N().S(` employees</li>
				</ul>
			</li>
			<li class="card__links-item">
				<a href="https://www.levels.fyi/companies/`)
		qw422016.E().S(company.LevelsFyiProfile.Alias)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Overview</a>
			</li>
			<li class="card__links-item">
				<a href="https://www.levels.fyi/companies/`)
		qw422016.E().S(company.LevelsFyiProfile.Alias)
		qw422016.N().S(`/jobs" target="_blank" class="button-link card__links-link">Jobs</a>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group">
			`)
	if company.GlassdoorProfile.OverviewURL == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title card__links-item--disabled">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="glassdoor icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/glassdoor.svg"
					/>
					<span class="card__links-link">Glassdoor</span>
				</div>
				<ul class="card__links-item-info">
					<li class="card__link-stats-item card__link-stats-item--one-line">
						<span>
							<strong>???</strong> jobs
						</span>
						<span>
							<strong>???</strong> reviews
						</span>
						<span>
							<strong>???</strong> salaries
						</span>
					</li>
				</ul>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Overview</span>
				<a href="`)
		qw422016.E().S(googleSearchGlassdoor(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Reviews</span>
				<span class="card__links-link-star">?.? ★</span>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Jobs</span>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="glassdoor icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/glassdoor.svg"
					/>
					<a href="`)
		qw422016.E().S(company.GlassdoorProfile.OverviewURL)
		qw422016.N().S(`" target="_blank" class="card__links-link">Glassdoor</a>
					`)
		if company.GlassdoorProfile.Verified {
			qw422016.N().S(`
					<span class="card__links-link card__links-link--verify">
						<img
							class="card__links-icon"
							alt="icon"
							src="/assets/images/pages/organizer/verified-emp.png"
						/>
					</span>
					`)
		}
		qw422016.N().S(`
				</div>
				<ul class="card__links-item-info">
					<li class="card__link-stats-item card__link-stats-item--one-line">
						<span>
							<strong>`)
		qw422016.E().S(formatGlassdoorJobs(company.GlassdoorProfile.Jobs))
		qw422016.N().S(`</strong> jobs
						</span>
						<span>
							<strong>`)
		qw422016.E().S(formatGlassdoorReviews(company.GlassdoorProfile.Reviews))
		qw422016.N().S(`</strong> reviews
						</span>
						<span>
							<strong>`)
		qw422016.E().S(formatGlassdoorSalaries(company.GlassdoorProfile.Salaries))
		qw422016.N().S(`</strong> salaries
						</span>
					</li>
				</ul>
			</li>
			<li class="card__links-item">
				<a href="`)
		qw422016.E().S(company.GlassdoorProfile.OverviewURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Overview</a>
			</li>
			<li class="card__links-item">
				<a href="`)
		qw422016.E().S(company.GlassdoorProfile.ReviewsURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Reviews</a>
				<span class="card__links-link-star">`)
		qw422016.E().S(formatGlassdoorReviewsRate(company.GlassdoorProfile.ReviewsRate))
		qw422016.N().S(` ★</span>
			</li>
			<li class="card__links-item">
				<a href="`)
		qw422016.E().S(company.GlassdoorProfile.JobsURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Jobs</a>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group">
			`)
	if company.IndeedProfile.Alias == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title card__links-item--disabled">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/indeed.png"
					/>
					<span class="card__links-link">Indeed</span>
				</div>
			</li>
			<li class="card__links-item card__links-item--disabled">
				<span class="button-link card__links-link">Overview</span>
				<a href="`)
		qw422016.E().S(googleSearchIndeed(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			<li class="card__links-item  card__links-item--disabled">
				<span class="button-link card__links-link">Jobs</span>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/indeed.png"
					/>
					<a href="https://www.indeed.com/cmp/`)
		qw422016.E().S(company.IndeedProfile.Alias)
		qw422016.N().S(`" target="_blank" class="card__links-link">Indeed</a>
				</div>
			</li>
			<li class="card__links-item">
				<a href="https://www.indeed.com/cmp/`)
		qw422016.E().S(company.IndeedProfile.Alias)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Overview</a>
			</li>
			<li class="card__links-item">
				<a href="https://www.indeed.com/cmp/`)
		qw422016.E().S(company.IndeedProfile.Alias)
		qw422016.N().S(`/jobs" target="_blank" class="button-link card__links-link">Jobs</a>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group">
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/investors.svg"
					/>
					<span class="card__links-link">Investors</span>
				</div>
			</li>
			`)
	if company.DealroomURL == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="Dealroom icon" width="20" height="20" src="/assets/images/pages/organizer/dealroom.png" />
				<span class="button-link card__links-link">Dealroom</span>
				<a href="`)
		qw422016.E().S(googleSearchDealroom(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item">
				<img class="card__links-icon" alt="Dealroom icon" width="20" height="20" src="/assets/images/pages/organizer/dealroom.png" />
				<a href="`)
		qw422016.E().S(company.DealroomURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Dealroom</a>
			</li>
			`)
	}
	qw422016.N().S(`
			`)
	if company.CrunchbaseURL == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="Crunchbase icon" width="20" height="20" src="/assets/images/pages/organizer/crunchbase.svg" />
				<span class="button-link card__links-link">Crunchbase</span>
				<a href="`)
		qw422016.E().S(googleSearchCrunchbase(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item">
				<img class="card__links-icon" alt="Crunchbase icon" width="20" height="20" src="/assets/images/pages/organizer/crunchbase.svg" />
				<a href="`)
		qw422016.E().S(company.CrunchbaseURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Crunchbase</a>
			</li>
			`)
	}
	qw422016.N().S(`
			`)
	if company.PitchbookURL == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="Pitchbook icon" width="20" height="20" src="/assets/images/pages/organizer/pitchbook.png" />
				<span class="button-link card__links-link">Pitchbook</span>
				<a href="`)
		qw422016.E().S(googleSearchPitchbook(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item">
				<img class="card__links-icon" alt="Pitchbook icon" width="20" height="20" src="/assets/images/pages/organizer/pitchbook.png" />
				<a href="`)
		qw422016.E().S(company.PitchbookURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Pitchbook</a>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group">
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<img
						class="card__links-icon"
						alt="linkedin icon"
						width="32"
						height="32"
						src="/assets/images/pages/organizer/query_stats.svg"
					/>
					<span class="card__links-link">Market</span>
				</div>
			</li>
			`)
	if company.YahooFinanceURL == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="Yahoo Finance icon" width="20" height="20" src="/assets/images/pages/organizer/yahoo.png" />
				<span class="button-link card__links-link">Yahoo Finance</span>
				<a href="`)
		qw422016.E().S(googleSearchYahooFinance(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item">
				<img class="card__links-icon" alt="Yahoo Finance icon" width="20" height="20" src="/assets/images/pages/organizer/yahoo.png" />
				<a href="`)
		qw422016.E().S(company.YahooFinanceURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Yahoo Finance</a>
			</li>
			`)
	}
	qw422016.N().S(`
			`)
	if company.GoogleFinanceURL == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="Google Finance icon" width="20" height="20" src="/assets/images/pages/organizer/google-fin.png" />
				<span class="button-link card__links-link">Google Finance</span>
				<a href="`)
		qw422016.E().S(googleSearchGoogleFinance(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item">
				<img class="card__links-icon" alt="Google Finance icon" width="20" height="20" src="/assets/images/pages/organizer/google-fin.png" />
				<a href="`)
		qw422016.E().S(company.GoogleFinanceURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Google Finance</a>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
	<div class="card">
		<ul class="card__links-group card__links-group--unbordered">
			<li class="card__links-item card__links-item--title">
				<div class="card__links-item-group">
					<span class="card__links-link">Other links</span>
				</div>
			</li>
			<li class="card__links-item">
				<img
					class="card__links-icon"
					alt="whois icon"
					width="20"
					height="20"
					src="/assets/images/pages/organizer/whois.svg"
				/>
				<a href="`)
	qw422016.E().S(whoisURL(company.Website))
	qw422016.N().S(`" target="_blank" class="button-link card__links-link">Whois</a>
			</li>
			<li class="card__links-item">
				<img
					class="card__links-icon"
					alt="similarweb icon"
					width="20"
					height="20"
					src="/assets/images/pages/organizer/similarweb.svg"
				/>
				<a href="`)
	qw422016.E().S(similarwebURL(company.Website))
	qw422016.N().S(`" target="_blank" class="button-link card__links-link">SimilarWeb</a>
			</li>
			`)
	if company.OttaProfileSlug == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="otta icon" width="20" height="20" src="/assets/images/pages/organizer/otta.svg" />
				<span class="button-link card__links-link">Otta</span>
				<a href="`)
		qw422016.E().S(googleSearchOtta(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item">
				<img class="card__links-icon" alt="otta icon" width="20" height="20" src="/assets/images/pages/organizer/otta.svg" />
				<a href="https://app.otta.com/companies/`)
		qw422016.E().S(company.OttaProfileSlug)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Otta</a>
			</li>
			`)
	}
	qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="xing icon" width="20" height="20" src="/assets/images/pages/organizer/xing.svg" />
				<span class="button-link card__links-link">XING</span>
				<a href="`)
	qw422016.E().S(googleSearchXing(company.Name))
	qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	if company.YCombinatorURL == "" {
		qw422016.N().S(`
			<li class="card__links-item card__links-item--disabled">
				<img class="card__links-icon" alt="Y Combinator icon" width="20" height="20" src="/assets/images/pages/organizer/y-combinator.png" />
				<span class="button-link card__links-link">Y Combinator</span>
				<a href="`)
		qw422016.E().S(googleSearchYCombinator(company.Name))
		qw422016.N().S(`" target="_blank" class="card__links-link card__links-link--google">
					<img class="card__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
				</a>
			</li>
			`)
	} else {
		qw422016.N().S(`
			<li class="card__links-item">
				<img class="card__links-icon" alt="Y Combinator icon" width="20" height="20" src="/assets/images/pages/organizer/y-combinator.png" />
				<a href="`)
		qw422016.E().S(company.YCombinatorURL)
		qw422016.N().S(`" target="_blank" class="button-link card__links-link">Y Combinator</a>
			</li>
			`)
	}
	qw422016.N().S(`
		</ul>
	</div>
</div></div>
</section>
<section class="company-vacancies">
	<div class="container company-vacancies__container">
		<h2 class="company-statistics__headline">Jobs</h2>
		`)
	qw422016.N().S(`
		<div class="vacancies__list">
			`)
	for _, vacancy := range vacancies {
		qw422016.N().S(`
				<div class="js-vacancy card"
					 data-vacancy-id="`)
		qw422016.N().DL(vacancy.ID)
		qw422016.N().S(`"
				>
					`)
		qw422016.N().S(`

					<aside class="card__action">
						`)
		if userVacancyFavoriteMap[vacancy.ID] {
			qw422016.N().S(`
						  <button class="js-vacancy-favorite favorite card__action-button button-group__item in-favorite" title="Remove from favorites">
							<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
							  <path
								d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
							  />
							</svg>
						  </button>
						`)
		} else {
			qw422016.N().S(`
						  <button class="js-vacancy-favorite favorite card__action-button button-group__item" title="Add to favorite">
							<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
							  <path
								d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
							  />
							</svg>
						  </button>
						`)
		}
		qw422016.N().S(`

						<button title="Hide vacancy" class="button-group__item button-group__item-sloth card__action-button-sloth"></button>
					</aside>
					<figure class="card__header card__header--organizer">
						<div class="card__image-overlay">
							<img class="card__image"
								alt="card image preview icon"
								src="`)
		qw422016.E().S(logo(company.Logo))
		qw422016.N().S(`"
							/>
						</div>
						<figcaption class="card__header-caption">
							<a href="/organizers/v/`)
		qw422016.N().DL(vacancy.ID)
		qw422016.N().S(`" target="_blank" class="card__headline vacancy__link">`)
		qw422016.E().S(vacancy.Title)
		qw422016.N().S(`</a>
							<a href="/organizers/`)
		qw422016.E().S(organizerFeature.Organizer.Alias)
		qw422016.N().S(`/companies/`)
		qw422016.E().S(vacancy.Company.Alias)
		qw422016.N().S(`" class="card__sub-headline vacancy__link">`)
		qw422016.E().S(vacancy.Company.Name)
		qw422016.N().S(`</a>
						</figcaption>
					</figure>
					<p class="card__text card__text--organizer">`)
		qw422016.E().S(vacancy.ShortDescription)
		qw422016.N().S(`</p>
					<div class="card__footer">
						<div class="card__details">
							<figure class="card__figure" title="`)
		qw422016.E().S(formatVacancyDate(vacancy.Date))
		qw422016.N().S(`">
								<img class="card__icon"
									alt="calendar icon"
									width="16"
									height="16"
									src="/assets/images/pages/online/calendar.svg"
								/>
								<figcaption class="card__figcaption">`)
		qw422016.E().S(formatVacancyDiffDate(vacancy.Date))
		qw422016.N().S(`</figcaption>
							</figure>
							<figure class="card__figure">
								<img class="card__icon"
									alt="eye icon"
									width="16"
									height="16"
									src="/assets/images/pages/common/eye.svg"
								/>
								<figcaption class="card__figcaption">Monthly views: `)
		qw422016.N().DL(vacancyMonthlyViewsMap[vacancy.ID])
		qw422016.N().S(`</figcaption>
							</figure>
						</div>
						<a href="/organizers/v/`)
		qw422016.N().DL(vacancy.ID)
		qw422016.N().S(`" target="_blank" class="button button--bordered-gray button--gap-images">
							`)
		if isLinkedInVacancyURL(vacancy.URL) {
			qw422016.N().S(`
								<img
									width="20"
									height="20"
									src="/assets/images/pages/organizer/linkedin.svg"
									alt="linkedin logo"
									class="hero__button-icon"
								/>
							`)
		} else if isOttaVacancyURL(vacancy.URL) {
			qw422016.N().S(`
								<img
									width="20"
									height="20"
									src="/assets/images/pages/organizer/otta.svg"
									alt="otta logo"
									class="hero__button-icon"
								/>
							`)
		} else if isIndeedVacancyURL(vacancy.URL) {
			qw422016.N().S(`
								<img
									width="20"
									height="20"
									src="/assets/images/pages/organizer/indeed.png"
									alt="indeed logo"
									class="hero__button-icon"
								/>
							`)
		}
		qw422016.N().S(`
							View source
							<img
								width="18"
								height="18"
								src="/assets/images/pages/common/external-link.svg"
								alt="arrow black icon"
								class="hero__button-icon"
							/>
						</a>
					</div>

					`)
		qw422016.N().S(`
				</div>
			`)
	}
	qw422016.N().S(`
		</div>
	</div>
</section>

<section class="company-statistics">
  <div class="container company-statistics__container">
    <h2 class="company-statistics__headline">Statistics</h2>
    <div class="stats">
      <header class="stats__head">
        <div class="stats__counters">
          <h3 class="stats__title">Views</h3>
          <div class="stats__counters-group">
            <div class="stats__counters-item">
              <p class="stats__counters-views">Total</p>
              <p class="stats__counters-item-number">`)
	qw422016.N().DL(stats.TotalViews)
	qw422016.N().S(`</p>
            </div>
            <div class="stats__counters-item">
              <p class="stats__counters-views">Last month</p>
              <p class="stats__counters-item-number">`)
	qw422016.N().DL(stats.LastMonthViews)
	qw422016.N().S(`</p>
            </div>
          </div>
        </div>
        <div class="stats__counters">
          <h3 class="stats__title">Added to favorites</h3>
          <div class="stats__counters-group">
            <div class="stats__counters-item">
              <p class="stats__counters-views">Total</p>
              <p class="stats__counters-item-number">`)
	qw422016.N().DL(stats.TotalFavorites)
	qw422016.N().S(`</p>
            </div>
            <div class="stats__counters-item">
              <p class="stats__counters-views">Last month</p>
              <p class="stats__counters-item-number">`)
	qw422016.N().DL(stats.LastMonthFavorites)
	qw422016.N().S(`</p>
            </div>
          </div>
        </div>
      </header>
      <div class="stats__item">
        <div class="stats__header">
          <h3 class="stats__title">Company website views</h3>
          <div class="stats__period">Last month</div>
        </div>
        <div class="stats__chart stats__chart--page-views-statistics js-chart-views-statistics"></div>
      </div>
    </div>
  </div>
</section>


</main>
`)
	streamorganizersFooter(qw422016)
	qw422016.N().S(`
<script src="/assets/js/organizers-company-app.js?`)
	qw422016.N().D(appVersion)
	qw422016.N().S(`"></script>
</body>
</html>
`)
}

func WriteOrganizersCompanyV2(qq422016 qtio422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamOrganizersCompanyV2(qw422016, organizerFeature, headerProfiles, company, vacancies, ukrainianUniversities, czechUniversities, favorite, userVacancyFavoriteMap, vacancyMonthlyViewsMap, stats, authQueryParams)
	qt422016.ReleaseWriter(qw422016)
}

func OrganizersCompanyV2(
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteOrganizersCompanyV2(qb422016, organizerFeature, headerProfiles, company, vacancies, ukrainianUniversities, czechUniversities, favorite, userVacancyFavoriteMap, vacancyMonthlyViewsMap, stats, authQueryParams)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
