// Code generated by qtc from "organizers-criteria-industry.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamorganizersCriteriaIndustry(qw422016 *qt422016.Writer) {
}

func writeorganizersCriteriaIndustry(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamorganizersCriteriaIndustry(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func organizersCriteriaIndustry() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writeorganizersCriteriaIndustry(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
