// Code generated by qtc from "organizers-company-v3.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamOrganizersCompanyV3(qw422016 *qt422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">

<head>
	<title>`)
	qw422016.E().S(company.Name)
	qw422016.N().S(` – company using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` | ReadyToTouch</title>
	<meta name="description" content="Improve your chances of getting a job by connecting with `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` developers from `)
	qw422016.E().S(company.Name)
	qw422016.N().S(` and receiving further recommendations.">

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="author" type="text/plain" href="https://readytotouch.com/humans.txt"/>
	<meta property="og:image" content="/assets/images/og/organizers-light.jpg">

    `)
	streamfavicon(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersFonts(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersCompanyV3Styles(qw422016)
	qw422016.N().S(`
    <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.52.0"></script>
    `)
	streamplausibleAnalytics(qw422016)
	qw422016.N().S(`
    `)
	streamga(qw422016)
	qw422016.N().S(`
</head>

<body>
<div class="main-wrapper main-wrapper--organizer-inner">
<header class="header">
  <div class="header__wrapper">
    <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`" class="header__logo">
      <img
        width="30"
        height="30"
        class="header__logo-img"
        src="/assets/images/pages/organizer/`)
	qw422016.E().S(organizerFeature.Organizer.Logo)
	qw422016.N().S(`"
        alt="organizer logo"
      />
      <span class="header__logo-label">Organizer</span>
    </a>
    <div class="header__nav-overlay js-header-nav">
      <ul class="header__nav">
        <li class="header__nav-item">
          <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/companies" class="header__nav-link active">Companies</a>
        </li>
        <li class="header__nav-item">
          <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/jobs" class="header__nav-link">Jobs</a>
        </li>
        `)
	qw422016.N().S(`
      </ul>
      `)
	streamorganizersHeaderStarsV3(qw422016)
	qw422016.N().S(`
      `)
	if len(headerProfiles) > 0 {
		qw422016.N().S(`
        `)
		streamorganizersHeaderProfileV3(qw422016, headerProfiles)
		qw422016.N().S(`
      `)
	} else {
		qw422016.N().S(`
        <a href="/`)
		qw422016.E().S(organizerFeature.Organizer.Alias)
		qw422016.N().S(`/welcome`)
		qw422016.E().S(authQueryParams)
		qw422016.N().S(`" class="button button--bordered-black button--small-padding header__login-button">Log in</a>
      `)
	}
	qw422016.N().S(`
    </div>
    `)
	streamorganizersHamburgerV3(qw422016)
	qw422016.N().S(`
  </div>
</header>

<main class="main-content">
  <div class="container">
    <nav aria-label="breadcrumb" aria-labelledby="navigation through the bread crumbs" class="breadcrumb">
      <ul class="breadcrumb__list">
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="/">Main</a>
        </li>
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`">`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(`</a>
        </li>
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="`)
	qw422016.E().S(organizerFeature.Path)
	qw422016.N().S(`">`)
	qw422016.E().S(organizerFeature.Title)
	qw422016.N().S(`</a>
        </li>
        <li class="breadcrumb__item">
          <span class="breadcrumb__page" aria-current="page">`)
	qw422016.E().S(company.Name)
	qw422016.N().S(`</span>
        </li>
      </ul>
    </nav>
  </div>

  <section class="company">
    <div class="container company__container">
      <svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <defs>
          <symbol id="icon-facebook" viewBox="0 0 32 32">
            <path fill="#4d515c" style="fill: var(--color1, #4d515c)" d="M32 16c0-8.836-7.164-16-16-16s-16 7.164-16 16c0 7.987 5.851 14.605 13.5 15.805v-11.179h-4.063v-4.627h4.063v-3.525c0-4.009 2.389-6.224 6.044-6.224 1.749 0 3.581 0.312 3.581 0.312v3.937h-2.019c-1.988 0-2.608 1.233-2.608 2.5v3h4.437l-0.709 4.625h-3.728v11.18c7.651-1.2 13.501-7.819 13.501-15.805z"></path>
            <path fill="#fff" style="fill: var(--color2, #fff)" d="M22.228 20.625l0.709-4.625h-4.437v-3c0-1.265 0.62-2.5 2.608-2.5h2.017v-3.937s-1.832-0.312-3.581-0.312c-3.655 0-6.044 2.213-6.044 6.224v3.525h-4.063v4.625h4.063v11.18c0.751 0.124 1.617 0.194 2.5 0.194s1.749-0.071 2.593-0.207l-0.093 0.012v-11.179h3.728z"></path>
          </symbol>
          <symbol id="icon-instagram" viewBox="0 0 32 32">
            <path fill="#4d515c" style="fill: var(--color1, #4d515c)" d="M16 2.88c4.275 0 4.781 0.020 6.463 0.095 1.563 0.069 2.407 0.332 2.968 0.551 0.721 0.27 1.335 0.676 1.838 1.192l0.001 0.001c0.561 0.563 0.907 1.093 1.193 1.837 0.219 0.563 0.48 1.413 0.549 2.969 0.076 1.687 0.093 2.193 0.093 6.463 0 4.275-0.017 4.781-0.093 6.461-0.068 1.563-0.331 2.407-0.549 2.969-0.288 0.744-0.637 1.281-1.193 1.837-0.503 0.518-1.117 0.925-1.805 1.182l-0.034 0.011c-0.561 0.22-1.412 0.481-2.968 0.551-1.688 0.075-2.193 0.093-6.463 0.093-4.275 0-4.781-0.019-6.463-0.093-1.563-0.069-2.407-0.331-2.968-0.551-0.721-0.27-1.335-0.676-1.838-1.192l-0.001-0.001c-0.518-0.503-0.924-1.117-1.182-1.803l-0.011-0.034c-0.219-0.563-0.48-1.413-0.549-2.969-0.076-1.687-0.093-2.193-0.093-6.461 0-4.276 0.017-4.781 0.093-6.463 0.068-1.563 0.331-2.407 0.549-2.969 0.288-0.744 0.637-1.28 1.193-1.837 0.563-0.563 1.093-0.907 1.839-1.193 0.561-0.219 1.412-0.481 2.968-0.551 1.681-0.075 2.187-0.093 6.463-0.093zM16 0c-4.344 0-4.888 0.019-6.593 0.093-1.7 0.076-2.869 0.351-3.881 0.744-1.111 0.424-2.058 1.054-2.836 1.849l-0.001 0.001c-0.795 0.778-1.425 1.723-1.832 2.777l-0.018 0.054c-0.393 1.019-0.668 2.181-0.744 3.881-0.075 1.712-0.093 2.256-0.093 6.6s0.019 4.888 0.093 6.593c0.076 1.7 0.351 2.869 0.744 3.881 0.413 1.056 0.956 1.951 1.851 2.837 0.778 0.793 1.723 1.42 2.777 1.826l0.054 0.018c1.019 0.395 2.181 0.669 3.881 0.744 1.707 0.075 2.251 0.093 6.593 0.093 4.344 0 4.888-0.019 6.595-0.093 1.7-0.075 2.868-0.349 3.88-0.744 1.108-0.423 2.053-1.051 2.831-1.843l0.001-0.001c0.793-0.778 1.42-1.723 1.826-2.777l0.018-0.054c0.393-1.019 0.668-2.181 0.744-3.881 0.075-1.707 0.093-2.251 0.093-6.593 0-4.344-0.019-4.888-0.093-6.595-0.076-1.7-0.351-2.868-0.744-3.88-0.408-1.116-1.033-2.067-1.83-2.842l-0.002-0.002c-0.778-0.793-1.723-1.42-2.777-1.826l-0.054-0.018c-1.019-0.393-2.181-0.671-3.881-0.744-1.712-0.080-2.256-0.1-6.6-0.1z"></path>
            <path fill="#4d515c" style="fill: var(--color1, #4d515c)" d="M16 7.781c-4.538 0.002-8.217 3.68-8.219 8.219v0c0.002 4.538 3.68 8.217 8.219 8.219h0c4.538-0.002 8.217-3.68 8.219-8.219v-0c-0.002-4.538-3.68-8.217-8.219-8.219h-0zM16 21.331c-2.944-0-5.331-2.387-5.331-5.332s2.387-5.332 5.332-5.332c0 0 0 0 0.001 0h-0c2.945 0 5.331 2.387 5.331 5.332s-2.387 5.332-5.332 5.332c-0 0-0 0-0.001 0h0zM26.463 7.456c0 0.015 0.001 0.033 0.001 0.051 0 1.060-0.86 1.92-1.92 1.92s-1.92-0.86-1.92-1.92c0-0.018 0-0.036 0.001-0.053l-0 0.003c0.028-1.038 0.877-1.869 1.919-1.869s1.891 0.831 1.919 1.867l0 0.003z"></path>
          </symbol>
          <symbol id="icon-reddit" viewBox="0 0 32 32">
            <path fill="#4d515c" style="fill: var(--color1, #4d515c)" d="M16 32c8.836 0 16-7.164 16-16s-7.164-16-16-16-16 7.164-16 16 7.164 16 16 16z"></path>
            <path fill="#fff" style="fill: var(--color2, #fff)" d="M26.667 16c0-1.291-1.048-2.339-2.339-2.339-0.637 0-1.199 0.243-1.609 0.653-1.591-1.14-3.8-1.889-6.232-1.983l1.067-4.996 3.461 0.729c0.037 0.892 0.768 1.601 1.665 1.601 0.92 0 1.667-0.746 1.667-1.667 0-0.003 0-0.006-0-0.009v0c0-0.917-0.749-1.667-1.667-1.667-0.653 0-1.216 0.376-1.477 0.937l-3.873-0.824c-0.025-0.005-0.055-0.008-0.085-0.008-0.087 0-0.168 0.024-0.238 0.065l0.002-0.001c-0.091 0.061-0.157 0.153-0.186 0.26l-0.001 0.003-1.179 5.576c-2.488 0.075-4.716 0.805-6.325 1.984-0.418-0.4-0.984-0.649-1.608-0.655h-0.001c-1.291 0-2.339 1.048-2.339 2.339 0 0.955 0.561 1.76 1.385 2.133-0.037 0.224-0.056 0.467-0.056 0.711 0 3.593 4.173 6.493 9.337 6.493 5.165 0 9.339-2.9 9.339-6.493 0-0.243-0.020-0.467-0.057-0.692 0.8-0.402 1.341-1.213 1.348-2.151v-0.001zM10.667 17.667c0-0.92 0.748-1.667 1.667-1.667 0.916 0 1.664 0.748 1.664 1.667 0 0.916-0.748 1.664-1.665 1.664s-1.665-0.748-1.665-1.665zM19.967 22.063c-1.141 1.143-3.312 1.217-3.948 1.217s-2.827-0.093-3.948-1.217c-0.078-0.079-0.126-0.188-0.126-0.309s0.048-0.229 0.127-0.309l-0 0c0.079-0.078 0.188-0.126 0.309-0.126s0.229 0.048 0.309 0.127l-0-0c0.711 0.712 2.245 0.973 3.349 0.973s2.62-0.263 3.349-0.973c0.079-0.079 0.189-0.127 0.309-0.127s0.23 0.049 0.309 0.127l-0-0c0.059 0.079 0.094 0.178 0.094 0.286 0 0.129-0.051 0.246-0.133 0.332l0-0zM19.668 19.331c-0.917 0-1.667-0.748-1.667-1.665s0.749-1.665 1.667-1.665 1.665 0.748 1.665 1.667c0 0.916-0.748 1.664-1.667 1.664z"></path>
          </symbol>
          <symbol id="icon-twitter_x" viewBox="0 0 32 32">
            <path fill="#4d515c" style="fill: var(--color1, #4d515c)" d="M24.435 2.539h4.499l-9.827 11.231 11.56 15.284h-9.052l-7.089-9.269-8.112 9.269h-4.501l10.511-12.013-11.089-14.501h9.281l6.408 8.472 7.413-8.472zM22.856 26.36h2.493l-16.089-21.271h-2.673l16.269 21.271z"></path>
          </symbol>
        </defs>
      </svg>

      <div
        class="js-company company-card"
        data-company-id="`)
	qw422016.N().DL(company.ID)
	qw422016.N().S(`"
        data-company-name="`)
	qw422016.E().S(company.Name)
	qw422016.N().S(`"
        data-company-type="`)
	qw422016.E().S(string(company.Type))
	qw422016.N().S(`"
      >
        <aside class="company-card__action">
          `)
	if favorite {
		qw422016.N().S(`
            <button class="js-company-favorite favorite company-card__action-button button-group__item in-favorite" title="Remove from favorites">
              <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
                <path
                  d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
                />
              </svg>
            </button>
          `)
	} else {
		qw422016.N().S(`
            <button class="js-company-favorite favorite company-card__action-button button-group__item" title="Add to favorite">
              <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
                <path
                  d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
                />
              </svg>
            </button>
          `)
	}
	qw422016.N().S(`
          `)
	qw422016.N().S(`
        </aside>
        <figure class="company-card__header">
          <div class="company-card__logo-overlay">
            `)
	if company.Logo.V2 != "" {
		qw422016.N().S(`
              <img
                class="company-card__logo"
                alt="`)
		qw422016.E().S(company.Name)
		qw422016.N().S(` logo"
                src="`)
		qw422016.E().S(logo72x72(company.Logo))
		qw422016.N().S(`"
              />
            `)
	}
	qw422016.N().S(`
          </div>
          <figcaption class="company-card__header-caption">
            <h1 class="company-card__headline vacancy__link">`)
	qw422016.E().S(company.Name)
	qw422016.N().S(`</h1>
            `)
	qw422016.N().S(`
            `)
	if !company.LatestVacancyDate.IsZero() {
		qw422016.N().S(`
            <p class="company-card__header-caption-text">
              <img
                class="company-card__header-caption-icon"
                alt="briefcase"
                width="12"
                height="12"
                src="/assets/images/pages/organizer/briefcase.svg"
              />Latest job posting: <time datetime="`)
		qw422016.E().S(company.LatestVacancyDate.Format(`2006-01-02`))
		qw422016.N().S(`">`)
		qw422016.E().S(company.LatestVacancyDate.Format("02 Jan 2006"))
		qw422016.N().S(`</time>
            </p>
            `)
	}
	qw422016.N().S(`
          </figcaption>
        </figure>
        <div class="company-card__top-links">
          <a href="`)
	qw422016.E().S(company.Website)
	qw422016.N().S(`" target="_blank" class="company-card__top-link button-link">Website</a>
          `)
	if company.Careers == "" {
		qw422016.N().S(`
            <span class="company-card__top-link button-link disabled">Careers</span>
          `)
	} else {
		qw422016.N().S(`
            <a href="`)
		qw422016.E().S(company.Careers)
		qw422016.N().S(`" target="_blank" class="company-card__top-link button-link">Careers</a>
          `)
	}
	qw422016.N().S(`
          `)
	if company.About == "" {
		qw422016.N().S(`
            <span class="company-card__top-link button-link disabled">About</span>
          `)
	} else {
		qw422016.N().S(`
            <a href="`)
		qw422016.E().S(company.About)
		qw422016.N().S(`" target="_blank" class="company-card__top-link button-link">About</a>
          `)
	}
	qw422016.N().S(`
          `)
	if company.Blog == "" {
		qw422016.N().S(`
            <span class="company-card__top-link button-link disabled">Dev Blog</span>
          `)
	} else {
		qw422016.N().S(`
            <a href="`)
		qw422016.E().S(company.Blog)
		qw422016.N().S(`" target="_blank" class="company-card__top-link button-link">Dev Blog</a>
          `)
	}
	qw422016.N().S(`
          `)
	qw422016.N().S(`
        </div>
        <div class="company-card__stacks">
          <p class="company-card__stacks-text">Other tech stacks for this company:</p>
            <ul class="company-card__stacks-list">
              `)
	for _, state := range companyOrganizers(company) {
		qw422016.N().S(`
              <li class="company-card__stacks-item">
                `)
		if state.Organizer.Alias == organizerFeature.Organizer.Alias {
			qw422016.N().S(`
                <a class="company-card__stacks-link company-card__stacks-link--current" href="/`)
			qw422016.E().S(state.Organizer.Alias)
			qw422016.N().S(`/companies/`)
			qw422016.E().S(company.LinkedInProfile.Alias)
			qw422016.N().S(`" title="`)
			qw422016.E().S(state.Organizer.Title)
			qw422016.N().S(`">
                  <img
                    class="company-card__stacks-image"
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/stacks/`)
			qw422016.E().S(state.Organizer.Logo)
			qw422016.N().S(`"
                    alt="`)
			qw422016.E().S(state.Organizer.Title)
			qw422016.N().S(`"
                  />
                </a>
                `)
		} else if state.Available {
			qw422016.N().S(`
                <a class="company-card__stacks-link" href="/`)
			qw422016.E().S(state.Organizer.Alias)
			qw422016.N().S(`/companies/`)
			qw422016.E().S(company.LinkedInProfile.Alias)
			qw422016.N().S(`" title="`)
			qw422016.E().S(state.Organizer.Title)
			qw422016.N().S(`">
                  <img
                    class="company-card__stacks-image"
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/stacks/`)
			qw422016.E().S(state.Organizer.Logo)
			qw422016.N().S(`"
                    alt="`)
			qw422016.E().S(state.Organizer.Title)
			qw422016.N().S(`"
                  />
                </a>
                `)
		} else {
			qw422016.N().S(`
                <a class="company-card__stacks-link company-card__stacks-link--disabled" href="javascript:void(0);" title="`)
			qw422016.E().S(state.Organizer.Title)
			qw422016.N().S(`">
                  <img
                    class="company-card__stacks-image"
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/stacks/`)
			qw422016.E().S(state.Organizer.Logo)
			qw422016.N().S(`"
                    alt="`)
			qw422016.E().S(state.Organizer.Title)
			qw422016.N().S(`"
                  />
                </a>
                `)
		}
		qw422016.N().S(`
              </li>
              `)
	}
	qw422016.N().S(`
            </ul>
        </div>
        <div class="company-card__info">
          <figure class="company-card__figure">
            <img
              class="company-card__icon"
              alt="card type icon"
              width="16"
              height="16"
              src="/assets/images/pages/vacancy/building.svg"
            />
            <figcaption class="company-card__figcaption">`)
	qw422016.E().S(companyTypeName[company.Type])
	qw422016.N().S(`</figcaption>
          </figure>
          <figure class="company-card__figure">
            <img
              class="company-card__icon"
              alt="card type icon"
              width="16"
              height="16"
              src="/assets/images/pages/vacancy/company-type.svg"
            />
            <figcaption class="company-card__figcaption">`)
	qw422016.E().S(industryNames(company.Industries))
	qw422016.N().S(`</figcaption>
          </figure>
          `)
	qw422016.N().S(`
        </div>
        <div class="company-card__info-group">
          <div class="company-card__info-group-content">
            <p class="company-card__text">`)
	qw422016.E().S(company.ShortDescription)
	qw422016.N().S(`</p>
          </div>
        </div>
        <div class="company-card__social">
          <p class="company-card__social-text">Social media:</p>
          <div class="company-card__social-links">
            <a href="javascript:void(0);"
               class="company-card__social-link company-card__social-link--disabled"
            >
              <svg class="company-card__social-image">
                <use xlink:href="#icon-instagram"></use>
              </svg>
            </a>
            <a href="javascript:void(0);"
               class="company-card__social-link company-card__social-link--disabled"
            >
              <svg class="company-card__social-image">
                <use xlink:href="#icon-reddit"></use>
              </svg>
            </a>
            <a href="javascript:void(0);"
               class="company-card__social-link company-card__social-link--disabled"
            >
              <svg class="company-card__social-image">
                <use xlink:href="#icon-twitter_x"></use>
              </svg>
            </a>
            <a href="javascript:void(0);"
               class="company-card__social-link company-card__social-link--disabled"
            >
              <svg class="company-card__social-image">
                <use xlink:href="#icon-facebook"></use>
              </svg>
            </a>
          </div>
        </div>
      </div>

      <div class="company-grid">
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="linkedin icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/linkedin.svg"
                />
                <a href="https://www.linkedin.com/company/`)
	qw422016.E().S(company.LinkedInProfile.Alias)
	qw422016.N().S(`/" target="_blank" class="company-grid__links-link">LinkedIn</a>
                `)
	if company.LinkedInProfile.Verified {
		qw422016.N().S(`
                <a href="https://www.linkedin.com/company/`)
		qw422016.E().S(company.LinkedInProfile.Alias)
		qw422016.N().S(`/about" target="_blank" class="company-grid__links-link company-grid__links-link--verify">
                  <img
                    class="company-grid__links-icon"
                    alt="icon"
                    src="/assets/images/pages/organizer/verified-icon.png"
                  />
                </a>
                `)
	}
	qw422016.N().S(`
              </div>
              <ul class="company-grid__links-item-info">
                <li class="company-grid__link-stats-item">`)
	qw422016.E().S(formatLinkedInFollowers(company.LinkedInProfile.Followers))
	qw422016.N().S(` followers</li>
                <li class="company-grid__link-stats-item">`)
	qw422016.E().S(formatLinkedInEmployees(company.LinkedInProfile.Employees))
	qw422016.N().S(` employees</li>
                <li class="company-grid__link-stats-item">`)
	qw422016.E().S(formatLinkedInAssociatedMembers(company.LinkedInProfile.AssociatedMembers))
	qw422016.N().S(` associated members</li>
              </ul>
            </li>
            <li class="company-grid__links-item">
              <a href="https://www.linkedin.com/company/`)
	qw422016.E().S(company.LinkedInProfile.Alias)
	qw422016.N().S(`/" target="_blank" class="button-link company-grid__links-link">Overview</a>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
	qw422016.E().S(linkedinConnectionsCEO(company))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">CEO</a>
            </li>
            <li class="company-grid__links-item company-grid__links-item--inner">
              <p class="company-grid__links-item-text">Connections (employees):</p>
              <ul class="company-grid__links-group-inner">
                <li class="company-grid__links-item">
                  <a href="`)
	qw422016.E().S(linkedinConnectionsURL([]Company{company}, nil))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Global</a>
                  <img
                    class="company-grid__links-icon"
                    alt="language icon"
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/language.svg"
                  />
                </li>
                <li class="company-grid__links-item">
                  <a href="`)
	qw422016.E().S(linkedinConnectionsURL([]Company{company}, ukrainianUniversities))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">UA</a>
                  <img
                    class="company-grid__links-icon"
                    alt="language icon"
                    width="20"
                    height="20"
                    src="/assets/images/pages/common/flags/4x3/ua.svg"
                  />
                </li>
                <li class="company-grid__links-item">
                  <a href="`)
	qw422016.E().S(linkedinConnectionsURL([]Company{company}, czechUniversities))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">CZ</a>
                  <img
                    class="company-grid__links-icon"
                    alt="language icon"
                    width="20"
                    height="20"
                    src="/assets/images/pages/common/flags/4x3/cz.svg"
                  />
                </li>
                <li class="company-grid__links-item">
                  <a href="`)
	qw422016.E().S(linkedinConnectionsFormerEmployeesURL([]Company{company}))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Former (All)</a>
                </li>
              </ul>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
	qw422016.E().S(linkedinEmployeesPostsURL([]Company{company}, organizerFeature.Organizer.Title))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Employees' posts</a>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
	qw422016.E().S(linkedinJobsURL([]Company{company}, string(organizerFeature.Organizer.LanguageTitleKeywords)))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Jobs</a>
            </li>
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            `)
	if company.GitHubProfile.Login == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title company-grid__links-item--disabled">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="GitHub icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/github.svg"
                />
                <span class="company-grid__links-link">GitHub</span>
              </div>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Overview</span>
              <a href="`)
		qw422016.E().S(googleSearchGitHub(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Repositories (?)</span>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Followers (?)</span>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="GitHub icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/github.svg"
                />
                `)
		if company.GitHubProfile.Verified {
			qw422016.N().S(`
                <span class="company-grid__links-link company-grid__links-link--verify">
                  <img
                    class="company-grid__links-icon"
                    alt="GitHub verified icon"
                    src="/assets/images/pages/organizer/verified.png"
                  />
                </span>
                `)
		}
		qw422016.N().S(`
                <a href="https://github.com/`)
		qw422016.E().S(company.GitHubProfile.Login)
		qw422016.N().S(`" target="_blank" class="company-grid__links-link">GitHub</a>
              </div>
            </li>
            <li class="company-grid__links-item">
              <a href="https://github.com/`)
		qw422016.E().S(company.GitHubProfile.Login)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Overview</a>
            </li>
            <li class="company-grid__links-item">
              <a href="https://github.com/orgs/`)
		qw422016.E().S(company.GitHubProfile.Login)
		qw422016.N().S(`/repositories?q=lang:`)
		qw422016.E().S(organizerFeature.Organizer.GitHubAlias)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Repositories (`)
		qw422016.N().D(fetchGitHubRepositoriesCount(company, organizerFeature.Organizer.Language))
		qw422016.N().S(`)</a>
            </li>
            <li class="company-grid__links-item">
              <a href="https://github.com/orgs/`)
		qw422016.E().S(company.GitHubProfile.Login)
		qw422016.N().S(`/followers" target="_blank" class="button-link company-grid__links-link">Followers (`)
		qw422016.E().S(fetchGitHubFollowers(company))
		qw422016.N().S(`)</a>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            `)
	if company.BlindProfile.Alias == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title company-grid__links-item--disabled">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="blind icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/blind.png"
                />
                <span class="company-grid__links-link">Blind</span>
              </div>
              <ul class="company-grid__links-item-info">
                <li class="company-grid__link-stats-item">??? employees</li>
                <li class="company-grid__link-stats-item">$??K ~ $???K a year</li>
                <li class="company-grid__link-stats-item">??? reviews</li>
              </ul>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Overview</span>
              <a href="`)
		qw422016.E().S(googleSearchBlind(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Reviews</span>
              <span class="company-grid__links-link-star">⭐ ?.?</span>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="blind icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/blind.png"
                />
                <a href="https://www.teamblind.com/company/`)
		qw422016.E().S(company.BlindProfile.Alias)
		qw422016.N().S(`" target="_blank" class="company-grid__links-link">Blind</a>
              </div>
              <ul class="company-grid__links-item-info">
                <li class="company-grid__link-stats-item">`)
		qw422016.E().S(formatBlindEmployees(company.BlindProfile.Employees))
		qw422016.N().S(` employees</li>
                <li class="company-grid__link-stats-item">`)
		qw422016.E().S(formatBlindSalary(company.BlindProfile.Salary))
		qw422016.N().S(`</li>
                <li class="company-grid__link-stats-item">`)
		qw422016.E().S(formatBlindReviews(company.BlindProfile.Reviews))
		qw422016.N().S(` reviews</li>
              </ul>
            </li>
            <li class="company-grid__links-item">
              <a href="https://www.teamblind.com/company/`)
		qw422016.E().S(company.BlindProfile.Alias)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Overview</a>
            </li>
            <li class="company-grid__links-item">
              <a href="https://www.teamblind.com/company/`)
		qw422016.E().S(company.BlindProfile.Alias)
		qw422016.N().S(`/reviews" target="_blank" class="button-link company-grid__links-link">Reviews</a>
              <span class="company-grid__links-link-star">⭐ `)
		qw422016.E().S(company.BlindProfile.ReviewsRate)
		qw422016.N().S(`</span>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            `)
	if company.LevelsFyiProfile.Alias == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title company-grid__links-item--disabled">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="levels.fyi icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/levels.png"
                />
                <span class="company-grid__links-link">Levels.fyi</span>
              </div>
              <ul class="company-grid__links-item-info">
                <li class="company-grid__link-stats-item">??? employees</li>
              </ul>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Overview</span>
              <a href="`)
		qw422016.E().S(googleSearchLevelsFyi(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Jobs</span>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="levels.fyi icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/levels.png"
                />
                <a href="https://www.levels.fyi/companies/`)
		qw422016.E().S(company.LevelsFyiProfile.Alias)
		qw422016.N().S(`" target="_blank" class="company-grid__links-link">Levels.fyi</a>
              </div>
              <ul class="company-grid__links-item-info">
                <li class="company-grid__link-stats-item">`)
		qw422016.E().S(formatLevelsFyiEmployees(company.LevelsFyiProfile.Employees))
		qw422016.N().S(` employees</li>
              </ul>
            </li>
            <li class="company-grid__links-item">
              <a href="https://www.levels.fyi/companies/`)
		qw422016.E().S(company.LevelsFyiProfile.Alias)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Overview</a>
            </li>
            <li class="company-grid__links-item">
              <a href="https://www.levels.fyi/companies/`)
		qw422016.E().S(company.LevelsFyiProfile.Alias)
		qw422016.N().S(`/jobs" target="_blank" class="button-link company-grid__links-link">Jobs</a>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            `)
	if company.GlassdoorProfile.OverviewURL == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title company-grid__links-item--disabled">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="glassdoor icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/glassdoor.svg"
                />
                <span class="company-grid__links-link">Glassdoor</span>
              </div>
              <ul class="company-grid__links-item-info">
                <li class="company-grid__link-stats-item company-grid__link-stats-item--one-line">
                  <span>
                    <strong>???</strong> jobs
                  </span>
                  <span>
                    <strong>???</strong> reviews
                  </span>
                  <span>
                    <strong>???</strong> salaries
                  </span>
                </li>
              </ul>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Overview</span>
              <a href="`)
		qw422016.E().S(googleSearchGlassdoor(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Reviews</span>
              <span class="company-grid__links-link-star">?.? ★</span>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Jobs</span>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="glassdoor icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/glassdoor.svg"
                />
                <a href="`)
		qw422016.E().S(company.GlassdoorProfile.OverviewURL)
		qw422016.N().S(`" target="_blank" class="company-grid__links-link">Glassdoor</a>
                `)
		if company.GlassdoorProfile.Verified {
			qw422016.N().S(`
                <span class="company-grid__links-link company-grid__links-link--verify">
                  <img
                    class="company-grid__links-icon"
                    alt="Glassdoor verified icon"
                    src="/assets/images/pages/organizer/verified-emp.png"
                  />
                </span>
                `)
		}
		qw422016.N().S(`
              </div>
              <ul class="company-grid__links-item-info">
                <li class="company-grid__link-stats-item company-grid__link-stats-item--one-line">
                  <span>
                    <strong>`)
		qw422016.E().S(formatGlassdoorJobs(company.GlassdoorProfile.Jobs))
		qw422016.N().S(`</strong> jobs
                  </span>
                  <span>
                    <strong>`)
		qw422016.E().S(formatGlassdoorReviews(company.GlassdoorProfile.Reviews))
		qw422016.N().S(`</strong> reviews
                  </span>
                  <span>
                    <strong>`)
		qw422016.E().S(formatGlassdoorSalaries(company.GlassdoorProfile.Salaries))
		qw422016.N().S(`</strong> salaries
                  </span>
                </li>
              </ul>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
		qw422016.E().S(company.GlassdoorProfile.OverviewURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Overview</a>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
		qw422016.E().S(company.GlassdoorProfile.ReviewsURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Reviews</a>
              <span class="company-grid__links-link-star">`)
		qw422016.E().S(formatGlassdoorReviewsRate(company.GlassdoorProfile.ReviewsRate))
		qw422016.N().S(` ★</span>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
		qw422016.E().S(company.GlassdoorProfile.JobsURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Jobs</a>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            `)
	if company.IndeedProfile.Alias == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title company-grid__links-item--disabled">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="indeed icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/indeed.png"
                />
                <span class="company-grid__links-link">Indeed</span>
              </div>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Overview</span>
              <a href="`)
		qw422016.E().S(googleSearchIndeed(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <span class="button-link company-grid__links-link">Jobs</span>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="indeed icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/indeed.png"
                />
                <a href="https://www.indeed.com/cmp/`)
		qw422016.E().S(company.IndeedProfile.Alias)
		qw422016.N().S(`" target="_blank" class="company-grid__links-link">Indeed</a>
              </div>
            </li>
            <li class="company-grid__links-item">
              <a href="https://www.indeed.com/cmp/`)
		qw422016.E().S(company.IndeedProfile.Alias)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Overview</a>
            </li>
            <li class="company-grid__links-item">
              <a href="https://www.indeed.com/cmp/`)
		qw422016.E().S(company.IndeedProfile.Alias)
		qw422016.N().S(`/jobs" target="_blank" class="button-link company-grid__links-link">Jobs</a>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="investors icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/investors.svg"
                />
                <span class="company-grid__links-link">Investors</span>
              </div>
            </li>
            `)
	if company.DealroomURL == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="Dealroom icon" width="20" height="20" src="/assets/images/pages/organizer/dealroom.png" />
              <span class="button-link company-grid__links-link">Dealroom</span>
              <a href="`)
		qw422016.E().S(googleSearchDealroom(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="Dealroom icon" width="20" height="20" src="/assets/images/pages/organizer/dealroom.png" />
              <a href="`)
		qw422016.E().S(company.DealroomURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Dealroom</a>
            </li>
            `)
	}
	qw422016.N().S(`
            `)
	if company.CrunchbaseURL == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="Crunchbase icon" width="20" height="20" src="/assets/images/pages/organizer/crunchbase.svg" />
              <span class="button-link company-grid__links-link">Crunchbase</span>
              <a href="`)
		qw422016.E().S(googleSearchCrunchbase(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="Crunchbase icon" width="20" height="20" src="/assets/images/pages/organizer/crunchbase.svg" />
              <a href="`)
		qw422016.E().S(company.CrunchbaseURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Crunchbase</a>
            </li>
            `)
	}
	qw422016.N().S(`
            `)
	if company.PitchbookURL == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="Pitchbook icon" width="20" height="20" src="/assets/images/pages/organizer/pitchbook.png" />
              <span class="button-link company-grid__links-link">Pitchbook</span>
              <a href="`)
		qw422016.E().S(googleSearchPitchbook(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="Pitchbook icon" width="20" height="20" src="/assets/images/pages/organizer/pitchbook.png" />
              <a href="`)
		qw422016.E().S(company.PitchbookURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Pitchbook</a>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group">
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <img
                  class="company-grid__links-icon"
                  alt="market icon"
                  width="32"
                  height="32"
                  src="/assets/images/pages/organizer/query_stats.svg"
                />
                <span class="company-grid__links-link">Market</span>
              </div>
            </li>
            `)
	if company.YahooFinanceURL == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="Yahoo Finance icon" width="20" height="20" src="/assets/images/pages/organizer/yahoo.png" />
              <span class="button-link company-grid__links-link">Yahoo Finance</span>
              <a href="`)
		qw422016.E().S(googleSearchYahooFinance(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="Yahoo Finance icon" width="20" height="20" src="/assets/images/pages/organizer/yahoo.png" />
              <a href="`)
		qw422016.E().S(company.YahooFinanceURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Yahoo Finance</a>
            </li>
            `)
	}
	qw422016.N().S(`
            `)
	if company.GoogleFinanceURL == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="Google Finance icon" width="20" height="20" src="/assets/images/pages/organizer/google-fin.png" />
              <span class="button-link company-grid__links-link">Google Finance</span>
              <a href="`)
		qw422016.E().S(googleSearchGoogleFinance(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="Google Finance icon" width="20" height="20" src="/assets/images/pages/organizer/google-fin.png" />
              <a href="`)
		qw422016.E().S(company.GoogleFinanceURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Google Finance</a>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group company-grid__links-group--unbordered">
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <span class="company-grid__links-link">Other links</span>
              </div>
            </li>
            <li class="company-grid__links-item">
              <img
                class="company-grid__links-icon"
                alt="whois icon"
                width="20"
                height="20"
                src="/assets/images/pages/organizer/whois.svg"
              />
              <a href="`)
	qw422016.E().S(whoisURL(company.Website))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Whois</a>
            </li>
            <li class="company-grid__links-item">
              <img
                class="company-grid__links-icon"
                alt="similarweb icon"
                width="20"
                height="20"
                src="/assets/images/pages/organizer/similarweb.svg"
              />
              <a href="`)
	qw422016.E().S(similarwebURL(company.Website))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Similarweb</a>
            </li>
            `)
	if company.OttaProfileSlug == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="otta icon" width="20" height="20" src="/assets/images/pages/organizer/otta.svg" />
              <span class="button-link company-grid__links-link">Otta</span>
              <a href="`)
		qw422016.E().S(googleSearchOtta(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="otta icon" width="20" height="20" src="/assets/images/pages/organizer/otta.svg" />
              <a href="https://app.otta.com/companies/`)
		qw422016.E().S(company.OttaProfileSlug)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Otta</a>
            </li>
            `)
	}
	qw422016.N().S(`
            `)
	if true {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="xing icon" width="20" height="20" src="/assets/images/pages/organizer/xing.svg" />
              <span class="button-link company-grid__links-link">XING</span>
              <a href="`)
		qw422016.E().S(googleSearchXing(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="xing icon" width="20" height="20" src="/assets/images/pages/organizer/xing.svg" />
              <a href="javascript:void(0);" target="_blank" class="button-link company-grid__links-link">XING</a>
            </li>
            `)
	}
	qw422016.N().S(`
            `)
	if company.YCombinatorURL == "" {
		qw422016.N().S(`
            <li class="company-grid__links-item company-grid__links-item--disabled">
              <img class="company-grid__links-icon" alt="ycombinator icon" width="20" height="20" src="/assets/images/pages/organizer/y-combinator.png" />
              <span class="button-link company-grid__links-link">Y Combinator</span>
              <a href="`)
		qw422016.E().S(googleSearchYCombinator(company.Name))
		qw422016.N().S(`" target="_blank" class="company-grid__links-link company-grid__links-link--google">
                <img class="company-grid__links-icon--google" alt="google icon" width="20" height="20" src="/assets/images/pages/organizer/google.svg">
              </a>
            </li>
            `)
	} else {
		qw422016.N().S(`
            <li class="company-grid__links-item">
              <img class="company-grid__links-icon" alt="ycombinator icon" width="20" height="20" src="/assets/images/pages/organizer/y-combinator.png" />
              <a href="`)
		qw422016.E().S(company.YCombinatorURL)
		qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">Y Combinator</a>
            </li>
            `)
	}
	qw422016.N().S(`
          </ul>
        </div>
        <div class="company-grid__item">
          <ul class="company-grid__links-group company-grid__links-group--unbordered">
            <li class="company-grid__links-item company-grid__links-item--title">
              <div class="company-grid__links-item-group">
                <span class="company-grid__links-link">Layoffs</span>
              </div>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
	qw422016.E().S(googleSearchLayoffsMonth(company.Name))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">In the past month</a>
            </li>
            <li class="company-grid__links-item">
              <a href="`)
	qw422016.E().S(googleSearchLayoffsYear(company.Name))
	qw422016.N().S(`" target="_blank" class="button-link company-grid__links-link">This year</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  `)
	if len(vacancies) > 0 {
		qw422016.N().S(`
  <section class="company-vacancies">
    <div class="container company-vacancies__container">
      <h2 class="company-vacancies__headline">Jobs</h2>
      `)
		qw422016.N().S(`
      <div class="company-vacancies__list">
        `)
		for _, vacancy := range vacancies {
			qw422016.N().S(`
        <div
          class="js-vacancy card"
          data-vacancy-id="`)
			qw422016.N().DL(vacancy.ID)
			qw422016.N().S(`"
        >
          <div class="card__vacancy">
            <aside class="card__action">
              `)
			if userVacancyFavoriteMap[vacancy.ID] {
				qw422016.N().S(`
                <button class="js-vacancy-favorite favorite card__action-button button-group__item in-favorite" title="Remove from favorites">
                  <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
                    <path
                      d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
                    />
                  </svg>
                </button>
              `)
			} else {
				qw422016.N().S(`
                <button class="js-vacancy-favorite favorite card__action-button button-group__item" title="Add to favorite">
                  <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" class="favorite__icon" viewBox="0 0 28 28">
                    <path
                      d="m14.5 22.1-.5-.3-.5.3-6.8 4.2c-.5.3-1.1-.1-.9-.7L7.5 18l.1-.6-.4-.4-5.9-5.2c-.3-.3-.3-.6-.2-.8.1-.2.3-.4.5-.4l7.9-.7.6-.1.2-.6 2.9-7.4c.2-.5 1-.5 1.2 0l3.1 7.3.2.5.6.1 7.9.7c.2 0 .4.2.5.5.1.3 0 .6-.2.7l-5.9 5.2-.4.4.1.6 1.8 7.7c.1.3 0 .5-.2.6-.2.1-.5.2-.8 0l-6.6-4z"
                    />
                  </svg>
                </button>
              `)
			}
			qw422016.N().S(`

              <button title="Hide vacancy" class="button-group__item button-group__item-sloth card__action-button-sloth"></button>
            </aside>

            <figure class="card__header card__header--organizer">
              <div class="card__logo-overlay">
                `)
			if vacancy.Company.Logo.V2 != "" {
				qw422016.N().S(`
                <img
                  class="card__logo"
                  alt="`)
				qw422016.E().S(vacancy.Company.Name)
				qw422016.N().S(` logo"
                  src="`)
				qw422016.E().S(logo72x72(vacancy.Company.Logo))
				qw422016.N().S(`"
                />
                `)
			}
			qw422016.N().S(`
              </div>
              <figcaption class="card__header-caption">
                <a href="/v/`)
			qw422016.N().DL(vacancy.ID)
			qw422016.N().S(`" target="_blank" class="card__headline">`)
			qw422016.E().S(vacancy.Title)
			qw422016.N().S(`</a>
                <a href="/`)
			qw422016.E().S(organizerFeature.Organizer.Alias)
			qw422016.N().S(`/companies/`)
			qw422016.E().S(vacancy.Company.Alias)
			qw422016.N().S(`" class="card__sub-headline">`)
			qw422016.E().S(vacancy.Company.Name)
			qw422016.N().S(`</a>
                `)
			if showLocation(vacancy.Location) {
				qw422016.N().S(`
                <p class="card__header-caption-text">
                  <img
                    class="card__header-caption-icon"
                    alt="marker"
                    width="12"
                    height="12"
                    src="/assets/images/pages/organizer/marker.svg"
                  />`)
				qw422016.E().S(vacancy.Location)
				qw422016.N().S(`&nbsp;`)
				if vacancy.Remote {
					qw422016.N().S(`(Remote)`)
				}
				qw422016.N().S(`
                </p>
                `)
			}
			qw422016.N().S(`
                `)
			qw422016.N().S(`
              </figcaption>
            </figure>

            <p class="card__text card__text--organizer">`)
			qw422016.E().S(vacancy.ShortDescription)
			qw422016.N().S(`</p>

            <div class="card__footer">
              <div class="card__details">
                <figure class="card__figure" title="`)
			qw422016.E().S(formatVacancyDate(vacancy.Date))
			qw422016.N().S(`">
                  <img
                    class="card__icon"
                    alt="calendar icon"
                    width="16"
                    height="16"
                    src="/assets/images/pages/online/calendar.svg"
                  />
                  <figcaption class="card__figcaption">`)
			qw422016.E().S(formatVacancyDiffDate(vacancy.Date))
			qw422016.N().S(`</figcaption>
                </figure>
                <figure class="card__figure" title="Monthly views: `)
			qw422016.N().DL(vacancyMonthlyViewsMap[vacancy.ID])
			qw422016.N().S(`">
                  <img
                    class="card__icon"
                    alt="eye icon"
                    width="16"
                    height="16"
                    src="/assets/images/pages/common/eye.svg"
                  />
                  <figcaption class="card__figcaption">Monthly views: `)
			qw422016.N().DL(vacancyMonthlyViewsMap[vacancy.ID])
			qw422016.N().S(`</figcaption>
                </figure>
              </div>
              <a href="/v/`)
			qw422016.N().DL(vacancy.ID)
			qw422016.N().S(`" target="_blank" class="button button--bordered-gray button--gap-images card__footer-button">
                `)
			if isLinkedInVacancyURL(vacancy.URL) {
				qw422016.N().S(`
                  <img
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/linkedin.svg"
                    alt="LinkedIn logo"
                    class="hero__button-icon"
                  />
                `)
			} else if isOttaVacancyURL(vacancy.URL) {
				qw422016.N().S(`
                  <img
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/otta.svg"
                    alt="Otta logo"
                    class="hero__button-icon"
                  />
                `)
			} else if isIndeedVacancyURL(vacancy.URL) {
				qw422016.N().S(`
                  <img
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/indeed.png"
                    alt="Indeed logo"
                    class="hero__button-icon"
                  />
                `)
			} else if isXingVacancyURL(vacancy.URL) {
				qw422016.N().S(`
                  <img
                    width="20"
                    height="20"
                    src="/assets/images/pages/organizer/xing.svg"
                    alt="XING logo"
                    class="hero__button-icon"
                  />
                `)
			}
			qw422016.N().S(`
                View source
                <img
                  width="18"
                  height="18"
                  src="/assets/images/pages/common/external-link.svg"
                  alt="arrow black icon"
                  class="hero__button-icon"
                />
              </a>
            </div>
          </div>
        </div>
        `)
		}
		qw422016.N().S(`
      </div>
    </div>
  </section>
  `)
	}
	qw422016.N().S(`

  `)
	qw422016.N().S(`

  <section class="company-statistics">
    <div class="container company-statistics__container">
      <h2 class="company-statistics__headline">Statistics</h2>
      <div class="stats">
        <header class="stats-caption">
          <div class="stats-caption__counters">
            <h3 class="stats-caption__title">Views</h3>
            <div class="stats-caption__counters-group">
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Total</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.TotalViews)
	qw422016.N().S(`</p>
              </div>
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Last month</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.LastMonthViews)
	qw422016.N().S(`</p>
              </div>
            </div>
          </div>
          <div class="stats-caption__counters">
            <h3 class="stats-caption__title">Added to favorites</h3>
            <div class="stats-caption__counters-group">
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Total</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.TotalFavorites)
	qw422016.N().S(`</p>
              </div>
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Last month</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.LastMonthFavorites)
	qw422016.N().S(`</p>
              </div>
            </div>
          </div>
        </header>
        <div class="stats__item">
          <div class="stats__header">
            <h3 class="stats__title">Company website views</h3>
            <div class="stats__period">Last month</div>
          </div>
          <div class="stats__chart stats__chart--page-views-statistics js-chart-views-statistics"></div>
        </div>
      </div>
    </div>
  </section>
</main>

`)
	streamorganizersFooterV3(qw422016)
	qw422016.N().S(`
</div>
<script src="/assets/js/organizers-company-app.js?`)
	qw422016.N().D(appVersion)
	qw422016.N().S(`"></script>
</body>

</html>
`)
}

func WriteOrganizersCompanyV3(qq422016 qtio422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamOrganizersCompanyV3(qw422016, organizerFeature, headerProfiles, company, vacancies, ukrainianUniversities, czechUniversities, favorite, userVacancyFavoriteMap, vacancyMonthlyViewsMap, stats, authQueryParams)
	qt422016.ReleaseWriter(qw422016)
}

func OrganizersCompanyV3(
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteOrganizersCompanyV3(qb422016, organizerFeature, headerProfiles, company, vacancies, ukrainianUniversities, czechUniversities, favorite, userVacancyFavoriteMap, vacancyMonthlyViewsMap, stats, authQueryParams)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
