// Code generated by qtc from "organizers-welcome-v3.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamOrganizersWelcomeV3(qw422016 *qt422016.Writer, organizer Organizer, authQueryParams string) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">

<head>
    <title>Welcome</title>
    <meta name="description" content="Welcome">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="author" type="text/plain" href="https://readytotouch.com/humans.txt"/>
    <meta property="og:image" content="/assets/images/og/organizers-light.jpg">

    `)
	streamfavicon(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersFonts(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersIndexV3Styles(qw422016)
	qw422016.N().S(`
    `)
	streamplausibleAnalytics(qw422016)
	qw422016.N().S(`
    `)
	streamga(qw422016)
	qw422016.N().S(`
</head>
<body>

<div class="main-wrapper">

<header class="header">
  <div class="header__wrapper">
    <a href="/" class="header__logo">
      <img width="40" height="40" class="header__logo-img" src="/assets/images/pages/organizer/`)
	qw422016.E().S(organizer.Logo)
	qw422016.N().S(`" alt="`)
	qw422016.E().S(organizer.Title)
	qw422016.N().S(` logo" />
      <h3 class="header__logo-title">Organizer</h3>
    </a>
    `)
	streamorganizersHeaderStarsV3(qw422016)
	qw422016.N().S(`
  </div>
</header>

<main class="main-content">
<section class="hero">
  <div class="hero__wrapper">
    <img
      class="hero__top-flag"
      alt="Flag of Ukraine with waves"
      width="24"
      height="24"
      src="/assets/images/pages/main-responsive/ua_flag_with_waves.svg"
    />
    <div class="hero__main">
      <h1 class="hero__title">Welcome</h1>
    </div>
    <div class="hero__buttons-group">
      `)
	qw422016.N().S(`
      <a href="/auth/github`)
	qw422016.E().S(authQueryParams)
	qw422016.N().S(`" class="button button--bordered-gray hero__button">
        <img
          width="20"
          height="20"
          src="/assets/images/pages/main-responsive/github-black.svg"
          alt="GitHub logo"
          class="button-icon"
        />Log in with GitHub
      </a>
      <a href="/auth/gitlab`)
	qw422016.E().S(authQueryParams)
	qw422016.N().S(`" class="button button--bordered-gray hero__button">
        <img
          width="20"
          height="20"
          src="/assets/images/pages/main-responsive/gitlab.svg"
          alt="GitLab logo"
          class="hero__button-icon"
        />Log in with GitLab
      </a>
      <a href="/auth/bitbucket`)
	qw422016.E().S(authQueryParams)
	qw422016.N().S(`" class="button button--bordered-gray hero__button">
        <img
          width="21"
          height="20"
          src="/assets/images/pages/main-responsive/bitbucket.svg"
          alt="Bitbucket logo"
          class="hero__button-icon"
        />Log in with Bitbucket
      </a>
    </div>
  </div>
</section>
</main>

`)
	streamorganizersFooterV3(qw422016)
	qw422016.N().S(`

</div>
<script src="/assets/js/welcome-app.js?`)
	qw422016.N().D(appVersion)
	qw422016.N().S(`"></script>
</body>
</html>
`)
}

func WriteOrganizersWelcomeV3(qq422016 qtio422016.Writer, organizer Organizer, authQueryParams string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamOrganizersWelcomeV3(qw422016, organizer, authQueryParams)
	qt422016.ReleaseWriter(qw422016)
}

func OrganizersWelcomeV3(organizer Organizer, authQueryParams string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteOrganizersWelcomeV3(qb422016, organizer, authQueryParams)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
