// Code generated by qtc from "organizer-vacancies-subscribe.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamOrganizerVacanciesSubscribe(qw422016 *qt422016.Writer) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">

<head>
	<title>Yet another anonymous work search</title>
	<meta name="description" content="Yet another anonymous work search">

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    `)
	streamfavicon(qw422016)
	qw422016.N().S(`

	<link rel='preload'
				href='/assets/fonts/montserrat/montserrat-latin-700.woff2'
				as='font'
				type='font/woff2'
				crossorigin
	>
	<link rel='preload'
				href='/assets/fonts/inter/inter-latin-regular.woff2'
				as='font'
				type='font/woff2'
				crossorigin
	>
	<link rel='preload'
				href='/assets/fonts/inter/inter-latin-500.woff2'
				as='font'
				type='font/woff2'
				crossorigin
	>

	`)
	streamorganizerVacanciesSubscribeStyles(qw422016)
	qw422016.N().S(`
</head>

<body class="organizer-inner">
<main class="main-wrapper">
	<header class="header">
  <div class="header__wrapper">
    <a href="#" class="header__logo">
      <img
        width="129"
        height="32"
        class="header__logo-img"
        src="/assets/images/pages/organizer/organizer.svg"
        alt="organizer logo"
      />
    </a>
    <ul class="header__nav">
      <li class="header__nav-item">
        <a href="/companies" class="header__nav-link">Companies</a>
      </li>
      <li class="header__nav-item">
        <a href="/vacancies" class="header__nav-link active">Vacancies</a>
      </li>
    </ul>
    <div class="header__stars">
      <iframe
        src="https://ghbtns.com/github-btn.html?user=readytotouch&repo=readytotouch.github.io&type=star&count=true&size=large"
        width="110"
        height="33"
        title="GitHub"
      ></iframe>
    </div>
    <div class="header__profile">
      <button class="header__profile-button">
        <img src="https://avatars.githubusercontent.com/u/63663261?v=4&s=48" alt="photo-profile" />
      </button>
      <div class="header__modal modal-profile">
        <div class="modal-profile__profile">
          <figure class="modal-profile__profile-info">
            <img
              src="https://avatars.githubusercontent.com/u/63663261?v=4&s=48"
              class="modal-profile__user-photo"
              width="48"
              height="48"
              alt="photo-profile"
            />
            <figcaption class="modal-profile__profile-name">Yaroslav Podorvanov</figcaption>
          </figure>
          <div class="modal-profile__profile-list">
            <a href="https://github.com/YaroslavPodorvanov" target="_blank" class="modal-profile__link">
              <img src="/assets/images/pages/online-new/github-black.svg" width="20" height="20" alt="GitHub logo" />
              <span class="modal-profile__profile-github">github.com/YaroslavPodorvanov</span>
            </a>
            <a href="https://gitlab.com/YaroslavPodorvanov" target="_blank" class="modal-profile__link">
              <img src="/assets/images/pages/online-new/gitlab.svg" width="20" height="20" alt="GitLab logo" />
              <span class="modal-profile__profile-gitlab">gitlab.com/YaroslavPodorvanov</span>
            </a>
          </div>
        </div>
        <div class="modal-profile__log-out">
          <a href="#" class="modal-profile__button">Log out</a>
        </div>
      </div>
    </div>
  </div>
</header>
<script>
  document.querySelector('.header__profile-button').addEventListener('click', () => {
    document.querySelector('.header__modal').classList.toggle('active')
  })
</script>



<div class="container">
  <nav aria-label="breadcrumb" aria-labelledby="navigation through the bread crumbs" class="breadcrumb">
    <ul class="breadcrumb__list">
      <li class="breadcrumb__item">
        <a class="breadcrumb__link" href="javascript:">Main</a>
      </li>
      <li class="breadcrumb__item">
        <a class="breadcrumb__link" href="javascript:">Organizer</a>
      </li>
      <li class="breadcrumb__item">
        <span class="breadcrumb__page" aria-current="page">Golang</span>
      </li>
    </ul>
  </nav>
</div>

<section class="hero">
  <div class="container hero__container">
    <div class="hero__overlay">
      <img
        class="hero__image"
        width="56"
        height="67"
        srcset="/assets/images/pages/organizer/eyes@2x.png 2x"
        src="/assets/images/pages/organizer/eyes.png"
        alt="eyes icon"
      />
      <h1 class="hero__headline">You've come across something we're still working on</h1>
      <p class="hero__description">Subscribe to be notified when this page is available</p>
      <a href="#" class="button button--small-padding button--black hero__button">Subscribe</a>
    </div>
  </div>
</section>

<section class="project-statistics">
  <div class="container project-statistics__container">
    <div class="stats">
      <div class="stats__item">
        <div class="stats__header">
          <h3 class="stats__title">Page views</h3>
        </div>
        <div class="stats__counters">
          <div class="stats__counters-item">
            <p class="stats__counters-views">Total views</p>
            <p class="stats__counters-item-number">846</p>
          </div>
          <div class="stats__counters-item">
            <p class="stats__counters-views">Last month's views</p>
            <p class="stats__counters-item-number">146</p>
          </div>
        </div>
        <div class="stats__chart stats__chart--page-views-statistics js-page-views-statistics"></div>
      </div>
      <div class="stats__item">
        <div class="stats__header">
          <h3 class="stats__title">Subscribers</h3>
        </div>
        <div class="stats__counters">
          <div class="stats__counters-item">
            <p class="stats__counters-views">Total subscribers</p>
            <p class="stats__counters-item-number">129</p>
          </div>
          <div class="stats__counters-item">
            <p class="stats__counters-views">Last month’s subscribers</p>
            <p class="stats__counters-item-number">63</p>
          </div>
        </div>
        <div class="stats__chart">
          <div class="stats__chart stats__chart--subscribers-statistics js-subscribers-statistics"></div>
        </div>
      </div>
    </div>
  </div>
</section>


</main>
<footer class="footer">
  <div class="footer__overlay">
    <div class="footer__wrapper">
      <div class="footer__group">
        <div class="footer__info">
          <a href="/" class="footer__title">
            <h3 class="footer__title-link">ReadyToTouch</h3>
          </a>
          <p class="footer__subtitle">Space to help you find jobs</p>
          <img width="98"
               height="64"
               loading="lazy"
               class="footer__ukraine-map"
               src="/assets/images/pages/online-new/ukraine-map.svg"
               alt="Map of Ukraine"
          >
        </div>
        <div class="footer__right-side">
          <iframe class="footer__stars"
                  src="https://ghbtns.com/github-btn.html?user=readytotouch&repo=readytotouch.github.io&type=star&count=true&size=large"
                  width="168"
                  height="33"
                  title="GitHub"
          ></iframe>
          <div class="footer__support">
            <a href="https://savelife.in.ua/en/" target="_blank" class="button button--bordered-gray footer__link">
              <figure class="footer__support-figure">
                <img width="49"
                     height="23"
                     src="/assets/images/pages/common-images/come_back_alive.svg"
                     alt="come back alive logo"
                >
                <figcaption class="footer__support-caption">Support</figcaption>
              </figure>
              <div class="footer__support-icon-box">
                <img width="18"
                     height="18"
                     src="/assets/images/pages/common/external-link.svg"
                     alt="external link icon"
                >
              </div>
            </a>
            <a href="https://war.ukraine.ua/" target="_blank" class="button button--bordered-gray footer__link">
              war.ukraine.ua
              <div class="footer__support-icon-box">
                <img width="18"
                     height="18"
                     src="/assets/images/pages/common/external-link.svg"
                     alt="external link icon"
                >
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="footer__copyrights">
        &copy; 2024 Yaroslav Podorvanov
        <img width="24"
             height="24"
             class="footer__flag-ua"
             src="/assets/images/pages/online-new/ua_flag_with_waves.svg"
             alt="Flag of Ukraine"
        >
      </div>
    </div>
  </div>
</footer>
<script src="/assets/js/organizer-vacancies_4801c60e30ec09e3b1f78ec58c31176c.js"></script>
</body>
</html>
`)
}

func WriteOrganizerVacanciesSubscribe(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamOrganizerVacanciesSubscribe(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func OrganizerVacanciesSubscribe() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteOrganizerVacanciesSubscribe(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
