// Code generated by qtc from "organizers-company-v3.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamOrganizersCompanyV3(qw422016 *qt422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">

<head>
	<title>`)
	qw422016.E().S(company.Name)
	qw422016.N().S(` – company using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` | ReadyToTouch</title>
	<meta name="description" content="Improve your chances of getting a job by connecting with `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` developers from `)
	qw422016.E().S(company.Name)
	qw422016.N().S(` and receiving further recommendations.">

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="author" type="text/plain" href="https://readytotouch.com/humans.txt"/>
	<meta property="og:image" content="/assets/images/og/organizers-light.jpg">

    `)
	streamfavicon(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersFonts(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersCompanyV3Styles(qw422016)
	qw422016.N().S(`
    <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.52.0"></script>
    `)
	streamplausibleAnalytics(qw422016)
	qw422016.N().S(`
    `)
	streamga(qw422016)
	qw422016.N().S(`
</head>

<body>
<div class="main-wrapper main-wrapper--organizer-inner">
<header class="header">
  <div class="header__wrapper">
    <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`" class="header__logo">
      <img
        width="30"
        height="30"
        class="header__logo-img"
        src="/assets/images/pages/organizer/`)
	qw422016.E().S(organizerFeature.Organizer.Logo)
	qw422016.N().S(`"
        alt="organizer logo"
      />
      <span class="header__logo-label">Organizer</span>
    </a>
    <div class="header__nav-overlay js-header-nav">
      <ul class="header__nav">
        <li class="header__nav-item">
          <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/companies" class="header__nav-link active">Companies</a>
        </li>
        <li class="header__nav-item">
          <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/jobs" class="header__nav-link">Jobs</a>
        </li>
        `)
	qw422016.N().S(`
      </ul>
      `)
	streamorganizersHeaderStarsV3(qw422016)
	qw422016.N().S(`
      `)
	if len(headerProfiles) > 0 {
		qw422016.N().S(`
        `)
		streamorganizersHeaderProfileV3(qw422016, headerProfiles)
		qw422016.N().S(`
      `)
	} else {
		qw422016.N().S(`
        <a href="/`)
		qw422016.E().S(organizerFeature.Organizer.Alias)
		qw422016.N().S(`/welcome`)
		qw422016.E().S(authQueryParams)
		qw422016.N().S(`" class="button button--bordered-black button--small-padding header__login-button">Log in</a>
      `)
	}
	qw422016.N().S(`
    </div>
    `)
	streamorganizersHamburgerV3(qw422016)
	qw422016.N().S(`
  </div>
</header>

<main class="main-content">
  <div class="container">
    <nav aria-label="breadcrumb" aria-labelledby="navigation through the bread crumbs" class="breadcrumb">
      <ul class="breadcrumb__list">
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="/">Main</a>
        </li>
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`">`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(`</a>
        </li>
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="`)
	qw422016.E().S(organizerFeature.Path)
	qw422016.N().S(`">`)
	qw422016.E().S(organizerFeature.Title)
	qw422016.N().S(`</a>
        </li>
        <li class="breadcrumb__item">
          <span class="breadcrumb__page" aria-current="page">`)
	qw422016.E().S(company.Name)
	qw422016.N().S(`</span>
        </li>
      </ul>
    </nav>
  </div>

  <section class="company"></section>

  <section class="company-vacancies"></section>

  <section class="sources-evidence"></section>

  <section class="company-statistics">
    <div class="container company-statistics__container">
      <h2 class="company-statistics__headline">Statistics</h2>
      <div class="stats">
        <header class="stats-caption">
          <div class="stats-caption__counters">
            <h3 class="stats-caption__title">Views</h3>
            <div class="stats-caption__counters-group">
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Total</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.TotalViews)
	qw422016.N().S(`</p>
              </div>
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Last month</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.LastMonthViews)
	qw422016.N().S(`</p>
              </div>
            </div>
          </div>
          <div class="stats-caption__counters">
            <h3 class="stats-caption__title">Added to favorites</h3>
            <div class="stats-caption__counters-group">
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Total</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.TotalFavorites)
	qw422016.N().S(`</p>
              </div>
              <div class="stats-caption__counters-item">
                <p class="stats-caption__counters-views">Last month</p>
                <p class="stats-caption__counters-item-number">`)
	qw422016.N().DL(stats.LastMonthFavorites)
	qw422016.N().S(`</p>
              </div>
            </div>
          </div>
        </header>
        <div class="stats__item">
          <div class="stats__header">
            <h3 class="stats__title">Company website views</h3>
            <div class="stats__period">Last month</div>
          </div>
          <div class="stats__chart stats__chart--page-views-statistics js-chart-views-statistics"></div>
        </div>
      </div>
    </div>
  </section>
</main>

`)
	streamorganizersFooterV3(qw422016)
	qw422016.N().S(`
</div>
<script src="/assets/js/organizers-company-app.js?`)
	qw422016.N().D(appVersion)
	qw422016.N().S(`"></script>
</body>
</html>
`)
}

func WriteOrganizersCompanyV3(qq422016 qtio422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamOrganizersCompanyV3(qw422016, organizerFeature, headerProfiles, company, vacancies, ukrainianUniversities, czechUniversities, favorite, userVacancyFavoriteMap, vacancyMonthlyViewsMap, stats, authQueryParams)
	qt422016.ReleaseWriter(qw422016)
}

func OrganizersCompanyV3(
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	company Company,
	vacancies []PreparedVacancy,
	ukrainianUniversities []University,
	czechUniversities []University,
	favorite bool,
	userVacancyFavoriteMap map[int64]bool,
	vacancyMonthlyViewsMap map[int64]int64,
	stats CompanyStats,
	authQueryParams string,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteOrganizersCompanyV3(qb422016, organizerFeature, headerProfiles, company, vacancies, ukrainianUniversities, czechUniversities, favorite, userVacancyFavoriteMap, vacancyMonthlyViewsMap, stats, authQueryParams)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
