// Code generated by qtc from "organizers-fonts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamorganizersFonts(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<link rel="preload"
            href="/assets/fonts/montserrat/montserrat-latin-700.woff2"
            as="font"
            type="font/woff2"
            crossorigin
>
<link rel="preload"
            href="/assets/fonts/inter/inter-latin-regular.woff2"
            as="font"
            type="font/woff2"
            crossorigin
>
<link rel="preload"
            href="/assets/fonts/inter/inter-latin-500.woff2"
            as="font"
            type="font/woff2"
            crossorigin
>
`)
}

func writeorganizersFonts(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamorganizersFonts(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func organizersFonts() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writeorganizersFonts(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
