// Code generated by qtc from "organizers-companies-v3-beta.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamOrganizersCompaniesV3Beta(qw422016 *qt422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	companies []Company,
	ukrainianUniversities []University,
	czechUniversities []University,
	userCompanyFavoriteMap map[int64]bool,
	authQueryParams string,
) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">

<head>
	<title>`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` companies – product and startup teams using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` | ReadyToTouch</title>
	<meta name="title" content="`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` companies – product and startup teams using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` | ReadyToTouch">
	<meta name="description" content="Discover companies using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` in production. This list features startups and product teams hiring `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` developers or already working with `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(`.">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="author" type="text/plain" href="https://readytotouch.com/humans.txt"/>

    <meta property="og:title" content="`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` companies | ReadyToTouch">
    <meta property="og:description" content="Discover startups and product teams using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` in production.">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://readytotouch.com/assets/images/og/organizers-light.jpg">
    <meta property="og:url" content="https://readytotouch.com/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/companies">

    <!-- JSON-LD (Schema.org) -->
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "WebPage",
      "name": "`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` companies",
      "description": "List of companies using `)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(` in production. Startups and product teams.",
      "url": "https://readytotouch.com/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/companies"
    }
    </script>

    `)
	streamfavicon(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersFonts(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersCompaniesV3Styles(qw422016)
	qw422016.N().S(`
    `)
	streamplausibleAnalytics(qw422016)
	qw422016.N().S(`
    `)
	streamga(qw422016)
	qw422016.N().S(`
</head>

<body>
<div class="main-wrapper main-wrapper--organizer-inner" data-companies-page-version="3-beta">
<header class="header">
  <div class="header__wrapper">
    <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`" class="header__logo">
      <img
        width="30"
        height="30"
        class="header__logo-img"
        src="/assets/images/pages/organizer/`)
	qw422016.E().S(organizerFeature.Organizer.Logo)
	qw422016.N().S(`"
        alt="organizer logo"
      />
      <span class="header__logo-label">Organizer</span>
    </a>
    <div class="header__nav-overlay js-header-nav">
      <ul class="header__nav">
        <li class="header__nav-item">
          <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/companies" class="header__nav-link active">Companies</a>
        </li>
        <li class="header__nav-item">
          <a href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`/jobs" class="header__nav-link">Jobs</a>
        </li>
        `)
	qw422016.N().S(`
      </ul>
      `)
	streamorganizersHeaderStarsV3(qw422016)
	qw422016.N().S(`
      `)
	if len(headerProfiles) > 0 {
		qw422016.N().S(`
        `)
		streamorganizersHeaderProfileV3(qw422016, headerProfiles)
		qw422016.N().S(`
      `)
	} else {
		qw422016.N().S(`
        <a href="/`)
		qw422016.E().S(organizerFeature.Organizer.Alias)
		qw422016.N().S(`/welcome`)
		qw422016.E().S(authQueryParams)
		qw422016.N().S(`" class="button button--bordered-black button--small-padding header__login-button">Log in</a>
      `)
	}
	qw422016.N().S(`
    </div>
    `)
	streamorganizersHamburgerV3(qw422016)
	qw422016.N().S(`
  </div>
</header>

<main class="main-content">
  <div class="container">
    <nav aria-label="breadcrumb" aria-labelledby="navigation through the bread crumbs" class="breadcrumb">
      <ul class="breadcrumb__list">
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="/">Main</a>
        </li>
        <li class="breadcrumb__item">
          <a class="breadcrumb__link" href="/`)
	qw422016.E().S(organizerFeature.Organizer.Alias)
	qw422016.N().S(`">`)
	qw422016.E().S(organizerFeature.Organizer.Title)
	qw422016.N().S(`</a>
        </li>
        <li class="breadcrumb__item">
          <span class="breadcrumb__page" aria-current="page">`)
	qw422016.E().S(organizerFeature.Title)
	qw422016.N().S(`</span>
        </li>
      </ul>
    </nav>
  </div>

  <section class="search-container container">
    <div class="search search--projects search--organizer search--with-sort">
      <div class="search__input-group">
        <form id="js-company-search-form">
          <input
            class="search__input"
            id="js-company-query"
            type="search"
            name="search"
            placeholder="Search"
          />
          `)
	qw422016.N().S(`
          <img class="search__icon" alt="Search icon" width="20" height="20" src="/assets/images/pages/common/search.svg" />
        </form>
      </div>
      <button type="button" class="mobile-filter js-mobile-open-filter-container-button">
        <img
          src="/assets/images/pages/common/filter.svg"
          alt="Filter icon"
          width="16"
          height="16"
        />
        <span id="js-mobile-selected-criteria-count" class="mobile-filter__counter" style="visibility: hidden;">0</span>
      </button>

      `)
	qw422016.N().S(`
    </div>
  </section>

  <div class="search-result mt-32">
    <div class="container">
      <div class="search-result__wrapper">
        <!-- filters -->
        <aside class="search-result__filters js-filter-container">
          <div class="search-result__filter-group search-result__filter-group--wide">
            <div class="search-result__filter-header">
              <h2 class="search-result__filter-headline">Filters:</h2>
              <button type="button" class="button button--light-link search-result__filter-headline-reset js-criteria-reset" style="visibility: hidden;">Reset all</button>
              <button type="button" class="button button--light-link search-result__filter-headline-reset-mobile js-mobile-close-filter-container-button">
                <img src="/assets/images/pages/common/cross-thin.svg" alt="cross icon" width="24" height="24">
              </button>
            </div>

            <div class="filters search-result__filters-list">
              `)
	qw422016.N().S(`

              <!-- Company type -->
              <div class="filters__group">
                <header class="filters__header filters__header--with-info">
                  <h4 class="filters__headline">Company type</h4>
                  `)
	qw422016.N().S(`
                </header>
                <div class="filters__elements">
                  <label class="checkbox filters__element">
                    <input class="js-criteria-company-type checkbox__input" type="checkbox" data-alias="product" />
                    <span class="checkbox__element"></span>
                    <span class="filters__element-text filters__element-text--truncated">Product</span>
                  </label>
                  <label class="checkbox filters__element">
                    <input class="js-criteria-company-type checkbox__input" type="checkbox" data-alias="startup" />
                    <span class="checkbox__element"></span>
                    <span class="filters__element-text filters__element-text--truncated">Startup</span>
                  </label>
                </div>
              </div>
              <!-- /Company type -->

              <!-- Industry -->
              <div class="filters__group">
                <header class="filters__header filters__header--with-info">
                  <h4 class="filters__headline">Industry</h4>
                  `)
	qw422016.N().S(`
                </header>
                <div class="filters__elements">
                  <div class="filters__elements-inner">
                    `)
	for _, industry := range industries {
		qw422016.N().S(`
                    <label class="checkbox filters__element">
                      <input class="js-criteria-company-industry checkbox__input" type="checkbox" data-alias="`)
		qw422016.E().S(industry.Alias)
		qw422016.N().S(`" />
                      <span class="checkbox__element"></span>
                      <span class="filters__element-text filters__element-text--truncated">`)
		qw422016.E().S(industry.Name)
		qw422016.N().S(`</span>
                    </label>
                    `)
	}
	qw422016.N().S(`
                  </div>
                </div>
              </div>
              <!-- /Industry -->

              <!-- Rating -->
              <div class="filters__group">
                <header class="filters__header filters__header--with-info">
                  <h4 class="filters__headline">Rating</h4>
                  <img
                    class="ml-8"
                    alt="Info icon"
                    width="16"
                    height="16"
                    title="info"
                    src="/assets/images/pages/common/glassdoor.svg"
                  />
                  `)
	qw422016.N().S(`
                </header>
                <div class="filters__elements filters__elements--full-height">
                  <label class="checkbox filters__element">
                    <input class="js-criteria-glassdoor-rating-rate checkbox__input" type="checkbox" data-alias="4.5" />
                    <span class="checkbox__element"></span>
                    <img
                      alt="Star icon"
                      width="22"
                      height="22"
                      title="info"
                      src="/assets/images/pages/common/star.svg"
                    />
                    <span class="filters__element-text filters__element-text--truncated">4.5 stars and above</span>
                  </label>
                  <label class="checkbox filters__element">
                    <input class="js-criteria-glassdoor-rating-rate checkbox__input" type="checkbox" data-alias="4.0" />
                    <span class="checkbox__element"></span>
                    <img
                      alt="Star icon"
                      width="22"
                      height="22"
                      title="info"
                      src="/assets/images/pages/common/star.svg"
                    />
                    <span class="filters__element-text filters__element-text--truncated">4.0 stars and above</span>
                  </label>
                  <label class="checkbox filters__element">
                    <input class="js-criteria-glassdoor-rating-rate checkbox__input" type="checkbox" data-alias="3.5" />
                    <span class="checkbox__element"></span>
                    <img
                      alt="Star icon"
                      width="22"
                      height="22"
                      title="info"
                      src="/assets/images/pages/common/star.svg"
                    />
                    <span class="filters__element-text filters__element-text--truncated">3.5 stars and above</span>
                  </label>
                  <label class="checkbox filters__element">
                    <input class="js-criteria-glassdoor-rating-rate checkbox__input" type="checkbox" data-alias="3.0" />
                    <span class="checkbox__element"></span>
                    <img
                      alt="Star icon"
                      width="22"
                      height="22"
                      title="info"
                      src="/assets/images/pages/common/star.svg"
                    />
                    <span class="filters__element-text filters__element-text--truncated">3.0 stars and above</span>
                  </label>
                </div>
              </div>
              <!-- /Rating -->

              <!-- Company size -->
              <div class="filters__group">
                <header class="filters__header filters__header--with-info">
                  <h4 class="filters__headline">Company size</h4>
                  <img
                    class="ml-8"
                    alt="LinkedIn icon"
                    width="16"
                    height="16"
                    title="info"
                    src="/assets/images/pages/common/linkedin-small.svg"
                  />
                  `)
	qw422016.N().S(`
                </header>
                <div class="filters__elements filters__elements--full-height">
                  `)
	for _, size := range []string{
		"2-10",    // 31
		"11-50",   // 161
		"51-200",  // 295
		"201-500", // 207
		"501-1K",  // 157
		"1K-5K",   // 214
		"5K-10K",  // 62
		"10K+",    // 173
	} {
		qw422016.N().S(`
                    <label class="checkbox filters__element">
                      <input class="js-criteria-linkedin-company-size checkbox__input" type="checkbox" data-alias="`)
		qw422016.E().S(size)
		qw422016.N().S(`" />
                      <span class="checkbox__element"></span>
                      <span class="filters__element-text filters__element-text--truncated">`)
		qw422016.E().S(size)
		qw422016.N().S(` employees</span>
                    </label>
                  `)
	}
	qw422016.N().S(`
                </div>
              </div>
              <!-- /Company size -->

              `)
	qw422016.N().S(`

              `)
	qw422016.N().S(`

              <!-- Other -->
              <div class="filters__group">
                <header class="filters__header filters__header--with-info">
                  <h4 class="filters__headline">Other</h4>
                  `)
	qw422016.N().S(`
                </header>
                <div class="filters__elements">
                  <label class="checkbox filters__element">
                    <input class="js-criteria-has-employees-from-country checkbox__input" type="checkbox" data-alias="ukraine" />
                    <span class="checkbox__element"></span>
                    <span class="filters__element-text filters__element-text--truncated">Has Ukrainian employees</span>
                    <img
                      class="checkbox__content-image"
                      alt="Flag of Ukraine"
                      width="24"
                      height="24"
                      src="/assets/images/pages/common/flags/4x3/ua.svg"
                    />
                  </label>
                  <label class="checkbox filters__element">
                    <input class="js-criteria-has-employees-from-country checkbox__input" type="checkbox" data-alias="czechia" />
                    <span class="checkbox__element"></span>
                    <span class="filters__element-text filters__element-text--truncated">Has Czechs employees</span>
                    <img
                      class="checkbox__content-image"
                      alt="Flag of Czechia"
                      width="24"
                      height="24"
                      src="/assets/images/pages/common/flags/4x3/cz.svg"
                    />
                  </label>
                  `)
	qw422016.N().S(`
                  `)
	if organizerFeature.Organizer.Alias == "rust" {
		qw422016.N().S(`
                  <label class="checkbox filters__element">
                    <input id="js-criteria-rust-foundation-members" class="checkbox__input" type="checkbox" />
                    <span class="checkbox__element"></span>
                    <span class="filters__element-text filters__element-text--truncated">Rust Foundation Members</span>
                  </label>
                  `)
	}
	qw422016.N().S(`
                  <label class="checkbox filters__element">
                    <input id="js-criteria-remote" class="checkbox__input" type="checkbox" />
                    <span class="checkbox__element"></span>
                    <span class="filters__element-text filters__element-text--truncated">Remote</span>
                  </label>
                  <label class="checkbox filters__element">
                    <input id="js-criteria-in-favorites" class="checkbox__input" type="checkbox" />
                    <span class="checkbox__element"></span>
                    <span class="filters__element-text filters__element-text--truncated">Favorites</span>
                  </label>
                </div>
              </div>
              <!-- /Other -->

            </div>
            <footer class="search-result__filter-footer">
              <button type="button" class="button button--light-link search-result__filter-footer-button js-criteria-reset">Reset all</button>
              <button type="button" class="button button--black button--small js-mobile-close-filter-container-button">Apply</button>
            </footer>
          </div>
        </aside>
        <!-- /filters -->

        <div class="search-result--group">
          <!-- selected filters -->
          <div class="filter-used" style="visibility: hidden;">
            <div class="filter-used__title">Applied filters:</div>
            <ul id="js-company-selected-criteria" class="filter-used__list"></ul>
          </div>
          <!-- /selected filters -->

          <div class="search-result__list">
            <div class="search-result__top-actions">
              <p class="search-result-found"><span id="js-result-count" class="search-result-found__amount"></span> results</p>
              `)
	qw422016.N().S(`
            </div>

            <!-- card list -->
            <div id="js-companies-container" class="search-result__cards row-gap-8 mt-24"></div>
            <!-- /card list -->

            <!-- search footer -->
            <footer class="search-result__footer">
              <div class="search-result__footer-action-list">
                <button id="js-pagination-show-more-button" class="button button--bordered-black-transparent d-none" type="button">Show more</button>
                <button id="js-pagination-show-all-button" class="button button--bordered-gray d-none" type="button">Show all (+<span id="js-pagination-show-all-count">0</span>)</button>
              </div>

              <!-- pagination -->
              <nav id="js-pagination-pages" class="pagination search-result__pagination"></nav>
              <!-- /pagination -->

            </footer>
            <!-- /search footer -->

          </div>
        </div>
      </div>
    </div>
  </div>

</main>

`)
	streamorganizersFooterV3(qw422016)
	qw422016.N().S(`
</div>
<script src="/assets/js/organizers-companies-v3-app.js?`)
	qw422016.N().D(appVersion)
	qw422016.N().S(`"></script>
</body>

</html>
`)
}

func WriteOrganizersCompaniesV3Beta(qq422016 qtio422016.Writer,
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	companies []Company,
	ukrainianUniversities []University,
	czechUniversities []University,
	userCompanyFavoriteMap map[int64]bool,
	authQueryParams string,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamOrganizersCompaniesV3Beta(qw422016, organizerFeature, headerProfiles, companies, ukrainianUniversities, czechUniversities, userCompanyFavoriteMap, authQueryParams)
	qt422016.ReleaseWriter(qw422016)
}

func OrganizersCompaniesV3Beta(
	organizerFeature OrganizerFeature,
	headerProfiles []SocialProviderUser,
	companies []Company,
	ukrainianUniversities []University,
	czechUniversities []University,
	userCompanyFavoriteMap map[int64]bool,
	authQueryParams string,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteOrganizersCompaniesV3Beta(qb422016, organizerFeature, headerProfiles, companies, ukrainianUniversities, czechUniversities, userCompanyFavoriteMap, authQueryParams)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
