// Code generated by qtc from "organizers-criteria-location.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamorganizersCriteriaLocation(qw422016 *qt422016.Writer) {
	qw422016.N().S(`  <div class="filters__group">
    <header class="filters__header filters__header--with-info">
      <h4 class="filters__headline">Location</h4>
      `)
	qw422016.N().S(`
    </header>
    <div class="filters__elements filters__elements--location">
      <div class="filters__elements-inner">
        `)
	qw422016.N().S(`
        `)
	for _, location := range criteriaLocations() {
		qw422016.N().S(`
          <label class="checkbox filters__element filters__element--location">
            <input class="js-criteria-location checkbox__input" type="checkbox" data-alias="`)
		qw422016.E().S(location.Code)
		qw422016.N().S(`" />
            <span class="checkbox__element"></span>
            <span class="fi fi-`)
		qw422016.E().S(location.Code)
		qw422016.N().S(`"></span>
            <span class="filters__element-text filters__element-text--truncated">`)
		qw422016.E().S(location.Name)
		qw422016.N().S(`</span>
          </label>
        `)
	}
	qw422016.N().S(`
      </div>
      `)
	qw422016.N().S(`
    </div>
  </div>
`)
}

func writeorganizersCriteriaLocation(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamorganizersCriteriaLocation(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func organizersCriteriaLocation() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writeorganizersCriteriaLocation(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
