// Code generated by qtc from "organizers-index-v3.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamOrganizersIndexV3(qw422016 *qt422016.Writer,
	headerProfiles []SocialProviderUser,
	socialProviderUsers []SocialProviderUser,
) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">

<head>
    <title>ReadyToTouch — Simplify Job Searching by Connecting with Developers</title>
    <meta name="description" content="ReadyToTouch is a platform that simplifies your job search. Connect directly with developers and boost your chances of getting hired through recommendations.">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="author" type="text/plain" href="https://readytotouch.com/humans.txt"/>
    <meta property="og:image" content="/assets/images/og/organizers-light.jpg">

    `)
	streamfavicon(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersFonts(qw422016)
	qw422016.N().S(`
    `)
	streamorganizersIndexV3Styles(qw422016)
	qw422016.N().S(`
    <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.52.0"></script>
    `)
	streamplausibleAnalytics(qw422016)
	qw422016.N().S(`
    `)
	streamga(qw422016)
	qw422016.N().S(`
</head>

<body>
<div class="main-wrapper">
<header class="header">
  <div class="header__wrapper">
    <a href="/" class="header__logo">
      <img width="40" height="40" class="header__logo-img" src="/assets/images/pages/online/logo.svg" alt="logo" />
      <h3 class="header__logo-title">ReadyToTouch</h3>
    </a>
    `)
	if len(headerProfiles) > 0 {
		qw422016.N().S(`
      <div class="header__nav-overlay js-header-nav">
        `)
		streamorganizersHeaderStarsV3(qw422016)
		qw422016.N().S(`
        `)
		streamorganizersHeaderProfileV3(qw422016, headerProfiles)
		qw422016.N().S(`
      </div>
      <button class="hamburger hamburger--spin header__hamburger js-hamburger"
        type="button"
        aria-expanded="false"
        aria-label="Open the menu"
      >
        <span class="hamburger__box">
          <span class="hamburger__inner"></span>
        </span>
      </button>
    `)
	} else {
		qw422016.N().S(`
    `)
		streamorganizersHeaderStarsV3(qw422016)
		qw422016.N().S(`
    `)
	}
	qw422016.N().S(`
  </div>
</header>

<main class="main-content">
</main>

`)
	streamorganizersFooterV3(qw422016)
	qw422016.N().S(`
</div>
<script src="/assets/js/online-stats-app.js?`)
	qw422016.N().D(appVersion)
	qw422016.N().S(`"></script>
</body>
</html>
`)
}

func WriteOrganizersIndexV3(qq422016 qtio422016.Writer,
	headerProfiles []SocialProviderUser,
	socialProviderUsers []SocialProviderUser,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamOrganizersIndexV3(qw422016, headerProfiles, socialProviderUsers)
	qt422016.ReleaseWriter(qw422016)
}

func OrganizersIndexV3(
	headerProfiles []SocialProviderUser,
	socialProviderUsers []SocialProviderUser,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteOrganizersIndexV3(qb422016, headerProfiles, socialProviderUsers)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
