// Code generated by qtc from "organizers-header-stars.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!--
//   110 for 1 digit
//   120 for 2 digit
//   ...
//   150 for 5 digits
// -->

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamorganizersHeaderStars(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div class="header__stars">
  <iframe
    src="https://ghbtns.com/github-btn.html?user=readytotouch&repo=readytotouch&type=star&count=true&size=large"
    width="150"
    height="33"
    title="GitHub"
  ></iframe>
</div>
`)
}

func writeorganizersHeaderStars(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamorganizersHeaderStars(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func organizersHeaderStars() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writeorganizersHeaderStars(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
