// Code generated by qtc from "registration_history-v3.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamregistrationHistoryV3(qw422016 *qt422016.Writer, socialProviderUsers []SocialProviderUser) {
	qw422016.N().S(`
`)
	if len(socialProviderUsers) > 0 {
		qw422016.N().S(`
<section class="history">
  <h2 class="history__title">Registration history</h2>
  <div class="history__table">
    <div class="history__table-header">
      <span class="history__name history__header-item">User name</span>
      <span class="history__profile history__header-item">Registration date</span>
    </div>
    <ul class="history__table-list">
      `)
		for _, profile := range socialProviderUsers {
			qw422016.N().S(`
      <li class="history__table-user">
        <div class="history__user-group">
          <img
            src="https://avatars.githubusercontent.com/u/`)
			qw422016.E().S(profile.SocialProviderUserID)
			qw422016.N().S(`?v=4&s=48"
            width="32"
            height="32"
            alt="photo"
            class="history__user-photo"
          />
          <span class="history__user-name">`)
			qw422016.E().S(SocialProviderUserName(profile))
			qw422016.N().S(`</span>
        </div>
        <span class="history__user-date history__user-item">`)
			qw422016.E().S(profile.CreatedAt.Format("January _2, 2006"))
			qw422016.N().S(`</span>
      </li>
      `)
		}
		qw422016.N().S(`
    </ul>
  </div>
</section>
`)
	}
	qw422016.N().S(`
`)
}

func writeregistrationHistoryV3(qq422016 qtio422016.Writer, socialProviderUsers []SocialProviderUser) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamregistrationHistoryV3(qw422016, socialProviderUsers)
	qt422016.ReleaseWriter(qw422016)
}

func registrationHistoryV3(socialProviderUsers []SocialProviderUser) string {
	qb422016 := qt422016.AcquireByteBuffer()
	writeregistrationHistoryV3(qb422016, socialProviderUsers)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
